export type Article = { slug: string; title: string; excerpt: string; image: string; category: string; paragraphs: string[]; checklist: string[]; serviceSlug: string };
export const articles: Article[] = [
  { slug: "pan-card-application-and-correction-jamshedpur", title: "PAN card application or correction in Jamshedpur: a practical checklist", excerpt: "What to check before starting a new PAN or correction request, which details must match, and what acknowledgement to keep.", image: "/images/blog/pan.png", category: "PAN services", paragraphs: ["A PAN application is easier when the applicant’s name, date of birth and supporting identity records agree. Before visiting a service centre in Kharangajhar, check whether you need a new PAN, a correction to an existing record, or a reprint. Duplicate applications can cause avoidable delays.", "Use the current official application route and follow its document, photograph and payment instructions. NISE COMPORT can help with form navigation and document preparation; the tax authority or authorised PAN service decides processing and issuance. Review every detail before submission and keep the acknowledgement number."], checklist: ["Confirm whether this is a new application, correction or reprint", "Check name and date of birth against supporting records", "Bring the proofs requested by the current official form", "Keep the acknowledgement and official payment receipt"], serviceSlug: "pan-card-application-jamshedpur" },
  { slug: "aadhaar-update-help-jamshedpur", title: "Aadhaar update help in Jamshedpur: know which updates need a centre", excerpt: "Understand the difference between online guidance and updates that require an authorised Aadhaar centre.", image: "/images/blog/aadhaar.png", category: "Aadhaar guidance", paragraphs: ["Aadhaar update options and requirements depend on the type of change. Some requests may be available online, while biometrics or other changes require an authorised centre. Confirm the current UIDAI process before travelling, and do not share your OTP or full credentials with anyone.", "NISE COMPORT can help you identify the right official route and prepare a checklist. We cannot change the Aadhaar record or guarantee approval; the responsible authority processes the request. Keep the acknowledgement slip so you can check status through official channels."], checklist: ["Identify the exact field or update you need", "Check the current official UIDAI instructions", "Carry original supporting documents when required", "Never share your OTP; retain the official acknowledgement"], serviceSlug: "aadhaar-update-guidance" },
  { slug: "jharkhand-income-caste-residence-certificates", title: "Jharkhand income, caste and residence certificate: documents to prepare", excerpt: "A locally useful preparation guide for common Jharkhand certificate applications and follow-up.", image: "/images/blog/certificate.png", category: "Jharkhand certificates", paragraphs: ["Certificate requirements depend on the certificate type, applicant circumstances and current Jharkhand portal instructions. Before starting, identify the exact certificate and check the current checklist published by the responsible department. Common application processes may request identity, address, family or income information, but do not rely on an old checklist as a guarantee.", "Bring the source documents requested by the official form and review spelling, addresses and supporting details carefully. NISE COMPORT can assist with portal navigation and submission steps in Jamshedpur. The issuing authority verifies evidence, decides eligibility and controls processing time."], checklist: ["Confirm the certificate type and applicant category", "Use the current official Jharkhand checklist", "Ensure names and addresses are consistent across proofs", "Save the application reference for status checks"], serviceSlug: "jharkhand-certificates-jamshedpur" },
  { slug: "voter-registration-correction-jharkhand", title: "Voter registration and correction in Jharkhand: a review checklist", excerpt: "Review the key details before an electoral-roll application or correction is submitted.", image: "/images/blog/voter.png", category: "Voter services", paragraphs: ["Electoral services include different request types, such as new registration, correction or address changes. Select the right request using the current Election Commission instructions. Incorrectly choosing a form can slow down the process.", "Check the applicant’s age, address and supporting documents against the official requirements. The election authority conducts verification and maintains the electoral roll; NISE COMPORT can help with online form navigation and the acknowledgement. Review the completed details yourself before submission."], checklist: ["Choose the correct registration or correction request", "Check eligibility and address proof requirements", "Review all entries before submission", "Keep the reference number for official follow-up"], serviceSlug: "voter-id-services-jamshedpur" },
  { slug: "bike-insurance-renewal-jamshedpur", title: "Renewing two-wheeler insurance in Jamshedpur: what to compare", excerpt: "Check coverage, exclusions and policy dates before choosing a motor-insurance renewal.", image: "/images/blog/insurance.png", category: "Insurance", paragraphs: ["Before renewing a two-wheeler policy, check the registration details, current policy end date, claims history and the coverage you need. Compare the insurer’s premium, exclusions, add-ons and claim process; the lowest quote may not provide the same cover as another option.", "NISE COMPORT can help with an enquiry and application steps where provider services are available. The insurer sets eligibility, premium, policy terms and claim decisions. Read the policy wording and retain the payment receipt and issued document."], checklist: ["Keep registration and existing policy details ready", "Compare coverage, exclusions and add-ons", "Verify the final premium directly with the insurer", "Save the issued policy and payment receipt"], serviceSlug: "bike-insurance-jamshedpur" },
  { slug: "passport-driving-licence-application-help", title: "Passport and driving licence applications: prepare before you book", excerpt: "A simple way to organise identity proofs, application details and official appointments.", image: "/images/blog/passport.png", category: "Application help", paragraphs: ["Passport and driving-licence requests follow separate official processes. Requirements can vary by application type, state, age and the issuing authority’s current rules. Read the official checklist before paying fees or scheduling an appointment.", "Make sure your name, address and date of birth match your supporting records. NISE COMPORT can assist with online form entry and appointment-step guidance, but appointments, tests, verification and issuance are controlled by the relevant authority."], checklist: ["Confirm the application type and current official requirements", "Check all personal details against original records", "Use the official portal for appointment and payment steps", "Keep acknowledgement, appointment and receipt details"], serviceSlug: "passport-driving-licence-help" },
  { slug: "online-form-filling-students-jharkhand", title: "Student and scholarship forms in Jharkhand: avoid common submission errors", excerpt: "Check eligibility, deadlines and uploads before submitting an admission, exam or scholarship form.", image: "/images/blog/7.png", category: "Education", paragraphs: ["Start with the official notification. Confirm the applicant category, eligibility, deadline and required document formats before entering information. A clear checklist helps students avoid last-minute issues such as mismatched names, expired documents or missing signature files.", "The student or guardian remains responsible for the accuracy of submitted details. NISE COMPORT can help with form navigation and upload preparation in Jamshedpur; the institution or department sets eligibility and makes the final decision."], checklist: ["Read the current official notification and deadline", "Prepare clear scans in the listed file formats", "Check name, school and bank details carefully", "Save the final form and acknowledgement"], serviceSlug: "student-scholarship-forms-jamshedpur" },
  { slug: "online-printing-upload-pickup-jamshedpur", title: "Online printing in Jamshedpur: upload, select pages and request pickup", excerpt: "How to use the NISE COMPORT print request flow without paying online at submission.", image: "/images/blog/11.png", category: "Printing", paragraphs: ["Upload your PDF or supported document after signing in, check the page count and preview, then enter page ranges such as 1-3, 5. Choose copies, paper and colour settings and request a pickup time or delivery. The request goes to the service desk for review.", "Submitting a print request is not an online checkout. NISE COMPORT confirms availability, delivery charges and the final quote before printing. Do not upload documents you are not authorised to share; account uploads are private and follow the site’s retention policy."], checklist: ["Review the preview and selected page ranges", "Choose colour, copies and pickup or delivery", "Submit the request for a staff-confirmed quote", "Proceed only after you approve the final estimate"], serviceSlug: "printing-scanning-jamshedpur" },
  { slug: "income-certificate-jharkhand-application", title: "Income certificate application in Jharkhand: preparation and follow-up", excerpt: "Organise the information for an income certificate application and understand who makes the decision.", image: "/images/blog/10.png", category: "Jharkhand certificates", paragraphs: ["Income certificate processes use details and evidence specified by the relevant Jharkhand authority. Requirements can change, so confirm the current list before applying. Organise household and income information carefully and ensure supporting records are legible.", "A service centre can assist with form navigation and submission, but it cannot certify eligibility or control approval timelines. Keep the reference number and check status through the official route."], checklist: ["Confirm current department instructions", "Prepare household and income information accurately", "Upload legible proofs in required formats", "Track the application with its acknowledgement"], serviceSlug: "jharkhand-certificates-jamshedpur" },
  { slug: "life-certificate-jeevan-pramaan-help", title: "Jeevan Pramaan life certificate: plan the submission carefully", excerpt: "What pensioners should check before using the current official digital life-certificate process.", image: "/images/blog/jeevanpraman.png", category: "Pension assistance", serviceSlug: "government-services", paragraphs: ["Jeevan Pramaan is a digital life-certificate service for eligible pensioners. Check current official instructions and supported submission methods before visiting. Bring only the information and documents requested by the authorised flow, complete required identity verification yourself and retain the acknowledgement for your pension authority. NISE COMPORT can provide navigation assistance where available; the pension-disbursing authority sets acceptance and processing rules."], checklist: ["Check current official instructions", "Confirm whether an authorised biometric step is required", "Keep the acknowledgement for follow-up"] },
];

// Public artwork and service explainers from the original NISE COMPORT media library.
export const galleryItems = [
  { title: "Digital citizen services", image: "/images/service/1.png", alt: "NISE COMPORT citizen service information artwork", category: "Services" },
  { title: "PAN application support", image: "/images/service/pan.png", alt: "PAN application assistance service artwork", category: "Government services" },
  { title: "Aadhaar guidance", image: "/images/service/aadhaar.png", alt: "Aadhaar service guidance artwork", category: "Government services" },
  { title: "Insurance enquiry", image: "/images/service/two-wheeler.png", alt: "Two wheeler insurance enquiry artwork", category: "Insurance" },
  { title: "Passport application help", image: "/images/service/passport.png", alt: "Passport application help service artwork", category: "Citizen services" },
  { title: "Online form assistance", image: "/images/service/5.png", alt: "Online application form support artwork", category: "Digital help" },
  { title: "Certificate checklist", image: "/images/service/4.png", alt: "Certificate document support artwork", category: "Jharkhand services" },
  { title: "Print and scan services", image: "/images/service/media.png", alt: "Printing and document services artwork", category: "Print & scan" },
  { title: "Community updates", image: "/images/slider/slide1.png", alt: "NISE COMPORT community service centre artwork", category: "Community" },
];
export const socialPosts = [
  { platform: "WhatsApp", title: "Need help with an online form?", text: "Bring the official form link and your supporting documents to our Kharangajhar desk. Message us first to check what to prepare.", image: "/images/offer/post/1.png", href: "https://wa.me/919771219893" },
  { platform: "Instagram", title: "Local help, with a clear next step", text: "PAN, certificates, insurance enquiries, printing and everyday digital services in Jamshedpur.", image: "/images/offer/post/2.png", href: "https://www.instagram.com/" },
  { platform: "YouTube", title: "Understand your service request", text: "We’re preparing short explainers for documents, applications and digital service requests. Check back for new videos.", image: "/images/offer/post/3.png", href: "https://www.youtube.com/" },
];
export const teamMembers = [
  { name: "Sanjay Kumar", role: "Head of Firm", image: "/images/team/1.png" },
  { name: "Chandrakala Devi", role: "Head of Finance", image: "/images/team/2.png" },
  { name: "Sanjana Shree", role: "Service team", image: "/images/team/10.png" },
  { name: "Gourav", role: "Service team", image: "/images/team/4.png" },
  { name: "Mitunjay", role: "Service team", image: "/images/team/7.png" },
  { name: "Jyoti Verma", role: "Service team", image: "/images/team/8.png" },
  { name: "Amarjeet Kumar", role: "Business partner", image: "/images/team/9.png" },
];
export const offerInfo = {
  title: "Current offers & customer vouchers",
  description: "NISE COMPORT shares limited offers and voucher codes here when they are available. Ask the team to confirm the eligible service, validity and conditions before you start.",
  note: "No discount is active by default. Customer coupons are checked against the live voucher list when you enter a code in a supported request flow. An offer does not reduce government, insurer or other third-party charges unless the offer terms explicitly say so.",
};
