export const panSources = {
  forms: "https://tinpan.proteantech.in/downloads/pan/downloads-pan.html",
  rules: "https://www.proteantech.in/articles/major-changes-pan-application-forms/",
  protean: "https://onlineservices.proteantech.in/paam/endUserRegisterContact.html",
  uti: "https://www.pan.utiitsl.com/PAN/",
  instant: "https://www.incometax.gov.in/iec/foportal/help/e-filing-generate-instant-e-pan-faq",
  proteanTrack: "https://tin.tin.proteantech.in/pantan/StatusTrack.html",
  utiTrack: "https://www.trackpan.utiitsl.com/PANONLINE/forms/TrackPan/trackApp",
  link: "https://eportal.incometax.gov.in/iec/foservices/#/pre-login/bl-link-aadhaar",
  linkStatus: "https://eportal.incometax.gov.in/iec/foservices/#/pre-login/link-aadhaar-status",
  epan: "https://onlineservices.proteantech.in/paam/requestAndDownloadEPAN.html",
};
export type PanGuide = { slug: string; title: string; intro: string; sections: { title: string; points: string[] }[]; faqs: { q: string; a: string }[]; links: { label: string; href: string }[] };
export const panGuides: PanGuide[] = [
  { slug: "application", title: "New PAN application", intro: "Choose the correct applicant route, prepare your documents and review every detail before submission.", sections: [
    { title: "Choose your route", points: ["First check whether a PAN is already allotted to you. A lost card is a reprint request, not a reason to obtain another PAN.", "Select citizenship separately from residence. An Indian citizen living abroad is not automatically a foreign citizen.", "Use the current individual or entity form. The official forms page lists Forms 93, 94, 95 and 96; the old 49A/49AA labels are historical."] },
    { title: "Your preparation checklist", points: ["Write the applicant name and date carefully from supporting records. Expand initials where the selected form requires it.", "Prepare the contact details, residence or office address and communication address requested for your category.", "Keep identity, address and birth or entity evidence ready. Check the current provider list rather than assuming one document meets every requirement."] },
    { title: "How NISE COMPORT assistance works", points: ["Choose a service and complete our guided assistance request. Saved profile details are offered for your review.", "Review the summary and send the request. Your private account receives a NISE request reference.", "Staff confirm the service scope, supporting documents and separate charges. Official submission happens through the applicable provider process.", "Retain the provider acknowledgement after official submission. It is different from the NISE service reference."] },
  ], faqs: [{ q: "Can I apply for a child?", a: "Use the minor route and include the parent or guardian contact. The official provider determines the representative and evidence requirements." }, { q: "Is there a guaranteed completion date?", a: "No. Document checks, discrepancies, provider processing and dispatch affect completion. Ask for an update using the acknowledgement from the provider." }, { q: "Will I pay on this website?", a: "This request does not take payment. The team confirms the assistance charge and any separate provider fee before proceeding." }], links: [{ label: "Protean online application", href: panSources.protean }, { label: "UTIITSL PAN services", href: panSources.uti }] },
  { slug: "correction", title: "PAN correction and personal changes", intro: "Use your existing PAN when updating a name, date, photo, signature, address or contact information.", sections: [
    { title: "Select only the changes you need", points: ["List the current discrepancy and the intended correct value. The PAN identifier normally stays the same for a correction.", "For a name change after marriage, prepare supporting evidence for the change and check the provider's current accepted list.", "For a minor-to-adult update, review photograph, signature and applicant details. Do not request a second PAN."] },
    { title: "Before sending documents", points: ["Use the current change-request form. Protean lists PAN CR-01 for individuals and PAN CR-02 for non-individuals.", "Make sure the new information is supported by the documents you submit. A spelling correction and a legal name change can require different evidence.", "Ask staff to explain any discrepancy message. Keep a copy of the final reviewed application and receipt."] },
  ], faqs: [{ q: "Can I change the PAN number itself?", a: "A correction concerns the details associated with an existing PAN. If you believe duplicate PANs were allotted, ask for surrender guidance rather than selecting a new PAN." }, { q: "Can a correction be edited after submission?", a: "It depends on the stage and provider. Contact the team promptly with the acknowledgement and correction needed; do not assume a submitted record can be edited." }], links: [{ label: "Current correction forms", href: panSources.forms }] },
  { slug: "aadhaar-linking", title: "PAN–Aadhaar linking", intro: "Check linking status, compare your records, and follow the Income Tax portal for the applicable linking process.", sections: [
    { title: "Check first", points: ["Use the official linking-status page before beginning another linking request.", "Check name, date of birth and other demographic details against the actual records. If they differ, identify which record needs correction.", "Confirm the applicable requirements and fee on the Income Tax portal. Never share the OTP received on your registered mobile."] },
    { title: "When linking fails", points: ["Save the exact error message without exposing identity numbers in public messages.", "Use the official correction or biometric-assistance route appropriate to the mismatch. Availability must be confirmed with the designated centre.", "If an overseas Indian citizen's status needs review, use the official jurisdictional officer guidance instead of assuming that every NRI has the same linking obligation."] },
  ], faqs: [{ q: "Does NISE COMPORT validate linking here?", a: "The official Income Tax portal confirms linking status. Our guide opens that portal; we do not claim to query its records." }, { q: "Is PAN application status the same as linking status?", a: "No. Application processing, PAN validity and PAN–Aadhaar linkage are different checks." }], links: [{ label: "Check linking status", href: panSources.linkStatus }, { label: "Official linking service", href: panSources.link }] },
  { slug: "status", title: "Track a PAN application", intro: "Choose the provider shown on your receipt. Prepare the correct reference before opening its official tracker.", sections: [
    { title: "Three different references", points: ["A NISE reference identifies your assistance request in your customer account.", "A Protean acknowledgement or UTIITSL coupon identifies the application submitted to that provider.", "A PAN is the tax identifier issued to the applicant. It is not an acknowledgement number or a postal tracking number."] },
    { title: "Follow the provider's result", points: ["Under processing means you should check for further instructions; it is not an approval promise.", "A discrepancy or documents-required message needs the specific correction requested by the provider.", "After dispatch, use the postal reference shown by the provider. Check the recorded delivery address when a card has not arrived.", "If no record is found, compare the provider and reference against your receipt before submitting another application."] },
  ], faqs: [{ q: "Will this site display the live provider status?", a: "No direct status integration is configured. The tool checks reference formatting and opens the official provider page, where verification is completed and live results appear." }, { q: "Is a correctly formatted reference proof of acceptance?", a: "No. A format check cannot prove that a reference exists or that the application was approved." }], links: [{ label: "Protean tracker", href: panSources.proteanTrack }, { label: "UTIITSL tracker", href: panSources.utiTrack }] },
  { slug: "epan", title: "Instant e-PAN and e-PAN downloads", intro: "Choose between applying for an eligible Instant e-PAN and downloading an electronic copy of a PAN already issued.", sections: [
    { title: "Instant e-PAN eligibility", points: ["The Income Tax FAQ describes this facility for eligible adults who have no PAN, have Aadhaar with a linked mobile, and are not covered by its representative-assessee restriction.", "Check that official eligibility page before starting. A minor or someone who already has a PAN should not use it to obtain another PAN."] },
    { title: "Download an existing e-PAN", points: ["Use the provider relevant to your PAN application. Download availability and any charge depend on that provider's terms and your application history.", "Complete any OTP or identity verification yourself on the official page.", "Read the email or provider instructions for the PDF password. Save the file privately and do not post the PDF or its password publicly."] },
  ], faqs: [{ q: "Are all e-PAN downloads free?", a: "No universal free-download promise applies. The eligible Instant e-PAN facility and provider downloads are separate services; check the selected portal's terms." }, { q: "Can I request a physical card after Instant e-PAN?", a: "UTIITSL lists a reprint route for eligible Instant e-PAN holders. Check its current instructions rather than applying for another PAN." }], links: [{ label: "Income Tax Instant e-PAN FAQ", href: panSources.instant }, { label: "Protean e-PAN download", href: panSources.epan }, { label: "UTIITSL download options", href: panSources.uti }] },
  { slug: "forms", title: "PAN forms and document preparation", intro: "Find the current official forms and organise evidence for the selected applicant category.", sections: [
    { title: "Current form map", points: ["Form 93: Indian individual. Form 94: Indian entity.", "Form 95: foreign individual. Form 96: foreign entity.", "For corrections, use the current individual or non-individual change-request form listed by the provider."] },
    { title: "Organise your evidence", points: ["Identity proof establishes who the applicant is; address proof supports the applicable address; birth evidence supports the date entered.", "Protean's April 2026 guidance says Aadhaar is not accepted as birth proof for the listed application modes. Check separate birth evidence with the current provider checklist.", "For an entity, prepare the relevant formation or registration record and authorised representative details. For minors, check guardian requirements.", "Keep photo and signature originals ready. Use the size, format and placement specified by the actual submission route; website intake limits are not official PAN portal limits."] },
  ], faqs: [{ q: "Can I keep using a saved Form 49A?", a: "Use the current official form downloads. The official providers announced replacement forms from April 2026." }, { q: "What is an AO code?", a: "It identifies an assessing-officer jurisdiction for the relevant application. Confirm it using the provider's official lookup or staff guidance; do not guess from a PIN code alone." }], links: [{ label: "Download official PAN forms", href: panSources.forms }, { label: "Protean 2026 changes", href: panSources.rules }] },
  { slug: "reprint", title: "Lost or damaged PAN card", intro: "Recover a card copy using the existing PAN. Decide whether the record also needs a correction before choosing reprint.", sections: [
    { title: "Reprint or correction?", points: ["Choose reprint when you need a replacement and the provider permits it for your existing record.", "If the name, photo, signature or communication information also needs changing, review the correction route first.", "Keep the earlier acknowledgement, a PAN copy if available, and current contact information ready. Ask the provider which evidence it needs for your situation."] },
    { title: "Delivery follow-up", points: ["Check the destination address and final charge on the official route before authorising a replacement.", "Save the acknowledgement and dispatch reference separately.", "If you have inadvertently been allotted multiple PANs, ask for surrender guidance; a reprint does not resolve duplicate allotment."] },
  ], faqs: [{ q: "Does a reprint create a different PAN?", a: "A reprint provides a card for an existing PAN; it is not a new allotment request." }, { q: "Can I request a plastic or smart card here?", a: "Confirm the official provider's card format and delivery options. We do not advertise an unofficial format as a distinct government PAN product." }], links: [{ label: "UTIITSL reprint options", href: panSources.uti }] },
  { slug: "issues", title: "PAN problems and next steps", intro: "Search the troubleshooting cards by the issue on your receipt or screen. Use the exact provider message when asking for help.", sections: [{ title: "Before retrying", points: ["Keep the provider acknowledgement and the date of the last attempt.", "Compare the actual error message with the submitted details. Avoid repeated payments or duplicate applications while an earlier transaction is unresolved.", "Contact NISE COMPORT with your service reference for assistance. Provider approval, refunds and official record changes remain with the relevant provider."] }], faqs: [{ q: "Can you promise a refund or approval?", a: "No. Review the provider's terms and the agreed assistance scope. We can help identify the next step, but cannot guarantee a provider decision." }], links: [{ label: "UTIITSL support and FAQs", href: panSources.uti }, { label: "Protean application portal", href: panSources.protean }] },
];
export const panIssues = [
  ["Application rejected", "Read the exact rejection reason. Prepare the requested correction or evidence and confirm the resubmission route before paying again."],
  ["Name mismatch", "Compare full names on the actual records. Identify which record needs changing and obtain evidence for the corrected name."],
  ["Photo rejected", "Use a clear current photo and the dimensions and file limits of your selected provider route."],
  ["Signature rejected", "Check clarity, placement, signatory capacity and the provider's current signature instructions."],
  ["Document upload failed", "Check the allowed file type and size, and make sure the file opens correctly. Retain the original before compressing."],
  ["Identity proof rejected", "Read the provider's accepted list and confirm the proof belongs to the applicant or permitted representative."],
  ["Address proof rejected", "Compare the communication address and proof. Check document age requirements where applicable."],
  ["Birth proof rejected", "Use a separate accepted birth document when required; do not assume Aadhaar is sufficient for the chosen mode."],
  ["Duplicate PAN detected", "Check existing records and ask for the appropriate correction or surrender route. Do not apply for another PAN."],
  ["Status not found", "Check the selected provider and reference against your receipt. An NISE service reference is not a provider acknowledgement."],
  ["Processing delayed", "Check for a discrepancy notice and retain the acknowledgement when contacting the provider."],
  ["Card not delivered", "Use the dispatch reference and compare the delivery address. Contact the provider or postal service about the actual tracking result."],
  ["OTP not received", "Check access to the registered contact, resend instructions and the official recovery route. Do not share received OTPs."],
  ["Payment debited but no receipt", "Keep the transaction reference and check the provider's pending-payment guidance before paying again."],
  ["Wrong AO code", "Use the provider's AO lookup or ask for jurisdiction guidance. Do not guess a replacement code."],
  ["Aadhaar linking failed", "Check the official linking status and demographic records; follow the specified correction or designated-centre route."],
  ["e-PAN download unavailable", "Check allotment and provider eligibility. Instant e-PAN and existing-provider downloads are different facilities."],
  ["PDF will not open", "Use the password instructions from the provider's message and a trusted PDF viewer; never upload the file to a public unlock service."],
] as const;
