export type ServiceGroup = { slug: string; title: string; description: string; keywords: string[] };
export type ServiceDetail = {
  slug: string; categorySlug: string; title: string; description: string; keywords: string[];
  highlights: string[]; documents: string[]; steps: string[]; faqs: { question: string; answer: string }[];
  /** Search result title (keep it short: the tab title starts with "NISE COMPORT - Pragya Kendra - "); defaults to the title. */
  seoTitle?: string;
  /** Meta description (≤ 160 characters); defaults to the description. */
  seoDescription?: string;
  /** Set to false to hide a service everywhere (pages, sitemap, links) without deleting it. */
  published?: boolean;
  /** Official source pages customers should check. */
  officialLinks?: { label: string; href: string }[];
};

export const serviceCatalog: ServiceGroup[] = [
  { slug: "banking", title: "Banking & Business Correspondent", description: "Assisted banking and payment services through available partner channels, with clear transaction confirmation and local help.", keywords: ["BC banking Jamshedpur", "AEPS Kharangajhar", "money transfer Telco"] },
  { slug: "government-services", title: "Government & Citizen Services", description: "Local guidance for PAN, Aadhaar-related assistance, voter services and Jharkhand certificate applications.", keywords: ["CSC Jamshedpur", "Pragya Kendra Kharangajhar", "Jharkhand online services"] },
  { slug: "insurance", title: "Insurance Assistance", description: "Get help reviewing information and submitting eligible motor, health, life and other insurance enquiries through participating providers.", keywords: ["bike insurance Jamshedpur", "car insurance Telco", "insurance help Jharkhand"] },
  { slug: "education", title: "Education & Student Services", description: "Practical support for admission, examination, scholarship and student application forms.", keywords: ["student form filling Jamshedpur", "scholarship application Telco", "admission form help Jharkhand"] },
  { slug: "fee-payments", title: "Fee, Bill & Recharge Payments", description: "Assistance with supported education fees, utility payments and recharges, with payment status or receipt where available.", keywords: ["bill payment Kharangajhar", "online fee payment Jamshedpur", "mobile recharge Telco"] },
  { slug: "form-filing", title: "Forms, Tax & Document Assistance", description: "Careful help with online forms, document preparation and submission steps for individuals and small businesses.", keywords: ["online form filling Jamshedpur", "ITR assistance Jharkhand", "GST form help Telco"] },
  { slug: "it-services", title: "IT, Printing & Digital Services", description: "Printing, scanning and computer-related assistance for households, students and local businesses.", keywords: ["printing Kharangajhar", "photocopy Telco", "computer service Jamshedpur"] },
  { slug: "travel", title: "Travel & Ticket Assistance", description: "Help with supported train, bus, flight and hotel searches or booking steps; final availability and fare are set by the travel provider.", keywords: ["train ticket help Jamshedpur", "bus booking Telco", "flight booking Jharkhand"] },
];

export const serviceDetails: ServiceDetail[] = [
  { slug: "pan-card", categorySlug: "government-services", title: "PAN Card Application & Correction in Jamshedpur", description: "Get local help with eligible new PAN applications, correction requests, document checks and application tracking in Kharangajhar, Telco.", keywords: ["PAN card apply Jamshedpur", "PAN correction Kharangajhar", "PAN card service Telco"], highlights: ["New PAN application guidance", "Correction and update request support", "Document checklist and form review", "Application acknowledgement guidance"], documents: ["Identity and date-of-birth proof accepted by the relevant PAN provider", "Address proof where required", "A recent photograph or signature if the selected process requests it"], steps: ["Tell us whether you need a new PAN or a correction.", "We explain the applicable provider checklist and service charges.", "Review your information before the application is submitted.", "Keep your acknowledgement and follow status through the provider."], faqs: [{ question: "Can NISE COMPORT guarantee PAN approval?", answer: "No. We facilitate the application. PAN issuance and processing are controlled by the authorised provider and tax authorities." }, { question: "Can I request a correction?", answer: "We can guide you through eligible correction requests after checking the provider's current process and supporting documents." }] },
  { slug: "aadhaar", categorySlug: "government-services", title: "Aadhaar Service Guidance in Jamshedpur", description: "Get help understanding available Aadhaar update routes, appointment requirements and supporting documents near Kharangajhar.", keywords: ["Aadhaar update help Jamshedpur", "Aadhaar appointment Kharangajhar", "Aadhaar guidance Telco"], highlights: ["Understand the correct update channel", "Review the document checklist", "Check whether an authorised centre appointment is needed", "Avoid sharing OTPs or biometrics outside the official process"], documents: ["Aadhaar number or enrolment details only when needed for guidance", "Original supporting proof accepted by UIDAI for the requested change"], steps: ["Describe the update you need.", "We explain whether it can be assisted here or requires an authorised Aadhaar centre.", "Use only the official process and retain your acknowledgement."], faqs: [{ question: "Can every Aadhaar update be completed at this desk?", answer: "No. Some updates require an authorised Aadhaar centre or official portal. We will explain the route before collecting any service charge." }] },
  { slug: "income-caste-residence-certificate", categorySlug: "government-services", title: "Income, Caste, Residence & EWS Certificate Help", description: "Local application assistance for eligible Jharkhand income, caste, residence and EWS certificate requests through the applicable government process.", keywords: ["income certificate Jamshedpur", "caste certificate Jharkhand", "residence certificate Kharangajhar", "EWS certificate Telco"], highlights: ["Income certificate application guidance", "Caste certificate document checklist", "Local/residential certificate support", "EWS application assistance"], documents: ["Applicant identity details", "Address and family information requested by the official form", "Supporting proofs required for the selected certificate and applicant category"], steps: ["Choose the certificate and confirm the applicant's eligibility route.", "Prepare the proofs listed by the responsible Jharkhand authority.", "Review the application before staff submit it through the official channel.", "Use the reference number for status follow-up."], faqs: [{ question: "How long will the certificate take?", answer: "Processing time is determined by the responsible authority and may vary. We cannot guarantee an approval date." }] },
  { slug: "voter-id", categorySlug: "government-services", title: "Voter ID & Electoral Services in Jamshedpur", description: "Guidance with eligible voter registration, correction and electoral-roll requests through the official election service process.", keywords: ["voter ID Jamshedpur", "EPIC correction Jharkhand", "new voter registration Telco"], highlights: ["New registration guidance", "Correction and address update support", "Application document review", "Reference number and status guidance"], documents: ["Age proof accepted by the election form", "Current address proof", "Applicant photograph and contact details if requested"], steps: ["Tell us whether you need registration, correction or another electoral service.", "Check the current form requirements and supporting proofs.", "Review the submitted details and retain the acknowledgement."], faqs: [{ question: "Does this desk issue voter cards?", answer: "No. We assist with the application process; the Election Commission handles verification and issuance." }] },
  { slug: "passport-driving-licence", categorySlug: "government-services", title: "Passport & Driving Licence Form Assistance", description: "Local form and document assistance for eligible passport and Jharkhand driving-licence processes, including guidance on official appointments.", keywords: ["passport form help Jamshedpur", "driving licence Jharkhand", "passport appointment Telco"], highlights: ["Online form entry support", "Document checklist guidance", "Appointment and fee-step guidance", "Application reference support"], documents: ["Identity and address proofs specified by the official portal", "Date-of-birth proof", "Existing licence or passport details for renewal or correction requests"], steps: ["Choose the correct official service and applicant category.", "Gather the documents listed by the issuing authority.", "Review the form and complete any required official appointment or payment.", "Keep the acknowledgement for follow-up."], faqs: [{ question: "Can NISE COMPORT approve my passport or licence?", answer: "No. Verification, appointments, testing, approval and issuance remain with the relevant authority." }] },
  { slug: "aeps-money-transfer", categorySlug: "banking", title: "Assisted Banking, AEPS & Money Transfer", description: "Ask about available Business Correspondent, AEPS, cash withdrawal, deposit and domestic transfer services at the Telco service desk.", keywords: ["AEPS Jamshedpur", "money transfer Kharangajhar", "banking correspondent Telco", "cash withdrawal Jamshedpur"], highlights: ["Available banking-partner transactions", "Account and basic service guidance", "Transaction acknowledgement where supported", "Clear confirmation before a transaction"], documents: ["Bank account or beneficiary details needed for the chosen service", "Identity verification required by the banking partner", "Registered mobile access when the partner requires it"], steps: ["Ask which partner service is currently available.", "Confirm the transaction amount and any partner/service charges.", "Complete required verification through the partner device or portal.", "Check the receipt and transaction status before leaving."], faqs: [{ question: "Are all bank services available every day?", answer: "Availability depends on partner systems, service hours and transaction limits. Contact us before travelling for a time-sensitive transaction." }, { question: "Should I share my banking OTP or PIN with staff?", answer: "Never disclose your PIN or OTP. Enter confidential credentials yourself through the authorised partner flow." }] },
  { slug: "bike-insurance", categorySlug: "insurance", title: "Two-Wheeler Insurance Assistance in Jamshedpur", description: "New bike or scooter insurance, renewal before or after expiry, and claim support. We compare quotes from several insurers and handle the paperwork; the insurer issues the policy and settles claims.", keywords: ["bike insurance Jamshedpur", "scooter insurance Telco", "two wheeler policy Kharangajhar", "bike insurance renewal Jamshedpur", "expired bike insurance renewal"], highlights: ["New two-wheeler: 1-year own damage + 5-year third party, or 5-year bundled", "Renewal before expiry with No Claim Bonus kept (20% to 50%)", "Expired policy renewal, with inspection arranged if the insurer asks", "Add-ons explained: zero depreciation, roadside help, engine, consumables", "Switch insurer and carry your NCB", "Claim support from intimation to settlement"], documents: ["RC (registration certificate), or the dealer invoice for a new vehicle", "Previous policy copy for renewal (and its NCB)", "Owner's Aadhaar or other ID and mobile number", "Driving licence (needed for claims)", "PUC certificate, if you have it", "For claims: photos of damage, FIR for theft or third-party injury"], steps: ["Tell us: new policy, renewal, expired policy or claim, with your vehicle details.", "We compare quotes, IDV and add-ons from insurers we work with.", "You choose; the policy is issued by the insurer in your name.", "We keep a reminder for your next renewal and help if you need to claim."], faqs: [{ question: "Is an insurance quote the final premium?", answer: "No. The insurer calculates the final premium and determines eligibility, coverage and issuance." }, { question: "Is third-party insurance compulsory for bikes?", answer: "Yes. Riding without at least third-party cover is an offence under the Motor Vehicles Act (₹2,000 fine and/or up to 3 months for a first offence)." }] },
  { slug: "car-insurance", categorySlug: "insurance", title: "Car Insurance & Renewal Assistance in Jamshedpur", description: "New car insurance, renewal before or after expiry, switching insurer with your NCB, and claim support. We compare quotes and do the paperwork; the insurer issues the policy and settles claims.", keywords: ["car insurance Jamshedpur", "car policy renewal Telco", "motor insurance Jharkhand", "expired car insurance renewal Jamshedpur", "zero depreciation car insurance"], highlights: ["New car: 1-year own damage + 3-year third party, or bundled", "Comprehensive, third-party-only or standalone own-damage cover", "Renewal with No Claim Bonus kept (20% to 50%)", "Expired policy renewal, with inspection arranged if needed", "Add-ons: zero dep, engine protect, return to invoice, NCB protect, key, tyre", "Cashless garage check near Jamshedpur and claim follow-up"], documents: ["RC, or the dealer invoice for a new car", "Previous policy copy for renewal (and its NCB)", "Owner's Aadhaar or other ID and mobile number", "Driving licence (needed for claims)", "PUC certificate, if you have it", "For claims: photos, repair estimate, FIR for theft or third-party injury"], steps: ["Tell us: new policy, renewal, expired policy or claim, with your car details.", "We compare premium, IDV, add-ons and cashless garages across insurers.", "You choose; the insurer issues the policy in your name.", "We remind you before the next renewal and support any claim until it's settled."], faqs: [{ question: "Does NISE COMPORT underwrite policies?", answer: "No. We facilitate enquiries. The insurer decides eligibility, coverage, premium and issuance." }, { question: "Comprehensive or third-party only?", answer: "Third-party is the legal minimum and pays for damage to others only. Comprehensive also covers your own car against accidents, theft, fire and floods. For most cars under 10 years old, comprehensive is worth it." }] },
  { slug: "health-life-insurance", categorySlug: "insurance", title: "Health, Life & Personal Insurance Enquiry Help", description: "Get local assistance understanding application steps for available health, life and personal-accident insurance products.", keywords: ["health insurance Jamshedpur", "life insurance Telco", "personal accident policy Jharkhand"], highlights: ["Provider enquiry support", "Application checklist guidance", "Help locating policy documents and proposal steps", "Clear explanation that terms are set by the insurer"], documents: ["Applicant details requested by the chosen insurer", "Age, nominee and contact details where requested", "Medical or income information only through the insurer's authorised process"], steps: ["Tell us the type of cover you are considering.", "Review the insurer's product information and exclusions.", "Submit accurate information directly through the provider's process.", "Read the policy wording and retain the issued documents."], faqs: [{ question: "Can you recommend or guarantee a claim outcome?", answer: "We can help with the application process, but policy suitability, underwriting and claim decisions belong to the insurer." }] },
  { slug: "scholarship-forms", categorySlug: "education", title: "Student, Scholarship & Admission Form Assistance", description: "Support with eligible admission, scholarship and education applications for students in Jamshedpur and nearby Jharkhand areas.", keywords: ["scholarship form Jamshedpur", "admission form help Telco", "student application Jharkhand"], highlights: ["Admission and scholarship form support", "Document upload guidance", "Application deadline checklist", "Acknowledgement and status support"], documents: ["Student identity and contact details", "Academic records and institution details", "Category, income or domicile proofs when the official scheme asks for them"], steps: ["Bring the form link or tell us the institution/scheme.", "Check the official eligibility and deadline.", "Review every entry and uploaded document before submission.", "Keep the confirmation or application number."], faqs: [{ question: "Can you confirm scholarship eligibility?", answer: "The relevant institution or department sets eligibility and makes the final decision. We help interpret the published checklist." }] },
  { slug: "exam-forms", categorySlug: "education", title: "Exam, Recruitment & Online Form Filling", description: "Careful local assistance with exam, recruitment and other online forms, including document uploads and payment-step guidance.", keywords: ["online form filling Jamshedpur", "exam form Telco", "job application help Jharkhand"], highlights: ["Exam and recruitment form entry", "Photo, signature and document upload checks", "Deadline and fee-step checklist", "Final applicant review before submission"], documents: ["Official notification and application link", "Applicant identity, education and category details requested by the form", "Photo, signature and supporting proofs in the stated format"], steps: ["Confirm the official form and last date.", "Prepare the exact information and documents listed in the notification.", "Review all entries yourself before the application is submitted.", "Save the final form, payment receipt and application number."], faqs: [{ question: "Will staff choose answers or certify my information?", answer: "No. The applicant is responsible for the truth and accuracy of all information and must review the form before submission." }] },
  { slug: "bill-payment-recharge", categorySlug: "fee-payments", title: "Online Fee, Utility Bill & Recharge Assistance", description: "Ask about supported school, college, utility, mobile and other digital payments at NISE COMPORT in Kharangajhar.", keywords: ["bill payment Jamshedpur", "recharge Telco", "school fee payment Kharangajhar"], highlights: ["Supported education fee payments", "Utility and recharge assistance", "Payment status check", "Receipt or transaction reference where available"], documents: ["Consumer, account or student reference number", "Correct bill or fee details", "Payment method required by the provider"], steps: ["Confirm the biller and exact amount due.", "Check any convenience or service fee before paying.", "Complete the payment through the provider channel.", "Verify the transaction result and keep its receipt."], faqs: [{ question: "What if a payment is pending?", answer: "Payment settlement and reversal depend on the biller or payment provider. Keep the transaction reference so we can help you check its status." }] },
  { slug: "itr-gst", categorySlug: "form-filing", title: "ITR, GST & Business Form Assistance", description: "Document preparation and portal-navigation support for eligible tax, GST and small-business form requests.", keywords: ["ITR assistance Jamshedpur", "GST form help Jharkhand", "business filing Telco"], highlights: ["Checklist and document organisation", "Portal navigation assistance", "Review of entered details with the applicant", "Filing acknowledgement guidance"], documents: ["Relevant financial or business records", "PAN and contact information", "Prior return or registration details if applicable"], steps: ["Describe the filing and tax period.", "Confirm the right service scope and any professional review needed.", "Provide accurate source records and review the prepared information.", "Retain the filing acknowledgement and any professional advice."], faqs: [{ question: "Is this legal or tax advice?", answer: "Routine portal assistance is not a substitute for advice from a qualified tax professional. Complex tax positions should be reviewed by one." }] },
  { slug: "printing-scanning", categorySlug: "it-services", title: "Online Printing, Scanning & Photocopy in Jamshedpur", description: "Upload a PDF, Word document or image, select pages and print options, then request pickup or delivery from Kharangajhar.", keywords: ["online printing Jamshedpur", "photocopy Kharangajhar", "document scanning Telco", "print shop near Telco"], highlights: ["Page-range selection and document preview", "Black-and-white or colour page selection", "Copies, paper size and orientation choices", "Scheduled pickup or delivery enquiry"], documents: ["PDF, Word document or supported image file", "A saved delivery address if requesting delivery"], steps: ["Sign in, upload your file and review the page count.", "Choose pages, colour, copies and finishing options.", "See an estimate and request the print job.", "Our team confirms availability and any delivery charge before printing."], faqs: [{ question: "Do I pay online to place a print request?", answer: "No online payment is taken in this version. The team confirms the final quote and payment method before proceeding." }, { question: "What are the current page estimates?", answer: "Black-and-white estimates use the configured tier rates; colour pages are estimated separately. The team confirms the final quote before printing." }] },
  { slug: "computer-repair", categorySlug: "it-services", title: "Computer, Printer & CCTV Assistance", description: "Ask about computer, printer, peripheral and CCTV sales or service enquiries for households and small businesses in Jamshedpur.", keywords: ["computer service Jamshedpur", "printer repair Telco", "CCTV installation Kharangajhar"], highlights: ["Computer and peripheral enquiries", "Printer and CCTV assistance", "Requirement-based product/service discussions", "Local contact and follow-up"], documents: ["Device brand and model", "Description of the issue or requested product", "Purchase proof or warranty information when requesting a repair"], steps: ["Share the device or installation requirement.", "We confirm whether the service is available and explain the next step.", "Review any estimate before approving repair or purchase."], faqs: [{ question: "Are all computer brands and parts in stock?", answer: "Availability changes. Contact the team with the model or requirement for a current answer." }] },
  { slug: "website-design", categorySlug: "it-services", title: "Website & Digital Support for Local Businesses", description: "Enquire about practical website, online listing and basic digital support for shops and service providers in East Singhbhum.", keywords: ["website support Jamshedpur", "digital services Jharkhand", "business website Telco"], highlights: ["Website requirement discussion", "Local business information setup guidance", "Small-business digital support enquiry"], documents: ["Business name and service summary", "Approved logo, photos and contact details", "Domain or hosting information if already available"], steps: ["Tell us your business goal and current online presence.", "We discuss scope and provide a separate estimate where available.", "Approve the scope before work begins."], faqs: [{ question: "Can you guarantee a search ranking?", answer: "No provider can guarantee a specific ranking. Search visibility depends on competition, useful content, technical quality and ongoing business signals." }] },
  { slug: "ticket-booking", categorySlug: "travel", title: "Train, Flight, Bus & Hotel Booking Assistance", description: "Get help searching supported travel options and completing booking steps; ticket availability, fare and cancellation rules come from the provider.", keywords: ["train booking Jamshedpur", "flight ticket Telco", "bus ticket Jharkhand", "hotel booking Jamshedpur"], highlights: ["Search and booking-step assistance", "Passenger detail review", "Fare and provider-rule check before payment", "Ticket or itinerary follow-up"], documents: ["Passenger names and ages as on identity documents", "Travel dates and route", "Contact details needed by the booking provider"], steps: ["Share your route, dates and traveller count.", "Review available options, fare, baggage and cancellation terms.", "Confirm passenger details and payment before ticketing.", "Keep the ticket and provider reference for changes or support."], faqs: [{ question: "Can you guarantee a fare or seat?", answer: "No. Fares and seats change until the provider confirms the booking." }] },

  { slug: "lic-policy", categorySlug: "insurance", title: "LIC Policy Information & Service Assistance", description: "Ask for help locating available LIC policy service routes, understanding basic online steps and organising policy documents in Jamshedpur.", keywords: ["LIC policy help Jamshedpur", "LIC service assistance Telco", "life insurance document help Jharkhand"], highlights: ["Identify a relevant policy service route", "Basic portal navigation and document checklist", "Premium receipt or policy document retrieval guidance", "Follow-up enquiry preparation"], documents: ["Policy number or policy document, if available", "Policyholder name and registered contact details", "The exact request, such as a premium receipt or status enquiry"], steps: ["Describe the LIC service you need and bring the policy reference if available.", "We identify the current official route and explain any assistance charge.", "You review and submit information through the official LIC process.", "Keep the official acknowledgement or receipt for follow-up."], faqs: [{ question: "Can NISE COMPORT change or approve my LIC policy?", answer: "No. We can help you navigate an available service route. LIC controls policy servicing, underwriting, claims and official records." }, { question: "Can you advise which life policy I should buy?", answer: "This page offers process assistance, not financial advice or a policy recommendation. Review product terms with LIC or an appropriately authorised adviser." }] },
  { slug: "mutual-fund-sip", categorySlug: "banking", title: "SIP & Mutual Fund Process Enquiry", description: "Get help understanding basic account and application steps for SIP or mutual-fund enquiries through an appropriately authorised provider, where available.", keywords: ["SIP enquiry Jamshedpur", "mutual fund process help Telco", "investment account assistance Jharkhand"], highlights: ["Basic process and document checklist", "Help locating an authorised provider channel", "Application navigation where currently available", "Clear separation between assistance and investment advice"], documents: ["PAN and identity details requested by the authorised provider", "Bank information entered only in the provider's secure process", "Registered mobile and email for provider verification"], steps: ["Tell us whether you need process information or help with an existing provider application.", "We confirm whether an authorised channel is available and explain any service charge.", "Review product risks, charges and documents with the provider before proceeding.", "Complete verification directly in the authorised provider process and save confirmations."], faqs: [{ question: "Will NISE COMPORT recommend a fund or promise returns?", answer: "No. This is process assistance only. Investments can go up or down; returns are not guaranteed. Seek advice from an appropriately authorised financial adviser." }, { question: "Can I share my OTP or investment credentials?", answer: "Never share OTPs, passwords or investment account credentials with staff. Enter them yourself only in the authorised provider process." }] },
  { slug: "rent-agreement", categorySlug: "form-filing", title: "Rent Agreement & NOC Form Assistance", description: "Get practical help organising information and navigating available rent agreement or no-objection certificate document processes in Jamshedpur.", keywords: ["rent agreement help Jamshedpur", "NOC form assistance Telco", "rental document support Jharkhand"], highlights: ["Information and document checklist", "Typing and formatting support for customer-provided terms", "Guidance on available stamp, registration or notarisation steps", "Referral for legal review where needed"], documents: ["Names and contact details of the parties", "Property address and customer-provided rental terms", "Identity or ownership documents requested for the selected process"], steps: ["Explain the document you need and its intended use.", "We confirm the available typing or form-assistance scope and quote before work begins.", "The parties review all terms and seek legal advice where appropriate.", "Complete any required stamp, registration, witnessing or notarisation with the relevant authority."], faqs: [{ question: "Is a typed agreement or NOC legal advice?", answer: "No. Document typing and process assistance are not legal advice. Parties should obtain legal review when rights, obligations or disputes are involved." }, { question: "Can you guarantee that a document will be accepted?", answer: "No. Acceptance depends on the receiving institution and applicable legal or registration requirements." }] },
  { slug: "fssai-license", categorySlug: "form-filing", title: "FSSAI Food Business Registration Assistance", description: "Ask about document preparation and portal navigation for eligible food business registration or licensing through the official FSSAI process.", keywords: ["FSSAI registration Jamshedpur", "food license help Telco", "FSSAI application Jharkhand"], highlights: ["Application route and document checklist", "Portal navigation and file-preparation assistance", "Application detail review with the business owner", "Acknowledgement and status guidance"], documents: ["Business owner and contact details requested by the current form", "Business address and food activity information", "Supporting records specified by the official eligibility route"], steps: ["Describe the food activity, business size and location.", "Check the current official FSSAI category and checklist before preparing the application.", "The business owner verifies declarations and information before submission.", "Keep the official acknowledgement and monitor status through the FSSAI channel."], faqs: [{ question: "Can NISE COMPORT issue an FSSAI licence?", answer: "No. We may assist with an eligible application process. FSSAI and the responsible authority determine category, verification, approval and issuance." }, { question: "Which FSSAI category do I need?", answer: "The correct category depends on current rules, business activity and scale. Confirm it using official FSSAI guidance before applying." }] },
  { slug: "udyam-registration", categorySlug: "form-filing", title: "Udyam & MSME Registration Assistance", description: "Get help understanding current Udyam portal steps and preparing information for an eligible micro, small or medium enterprise registration.", keywords: ["Udyam registration Jamshedpur", "MSME registration help Telco", "Udyam portal assistance Jharkhand"], highlights: ["Udyam portal navigation assistance", "Business information and checklist preparation", "Applicant review before submission", "Acknowledgement and registration-status guidance"], documents: ["PAN and Aadhaar details required by the current official process", "Business name, activity and contact details", "Bank or enterprise information requested by the official portal"], steps: ["Confirm whether you need a new registration or an update to an existing record.", "Review the official portal's current eligibility and information requirements.", "The business owner verifies declarations and completes required authentication.", "Save the official acknowledgement and use the portal for status or certificate access."], faqs: [{ question: "Does NISE COMPORT issue an MSME certificate?", answer: "No. Udyam registration is handled through the official government portal. We can assist with navigation and preparation; the portal issues the registration record." }, { question: "Is Udyam registration free on the official portal?", answer: "Check the current official Udyam portal for its latest terms. Any separate assistance charge will be explained before you proceed." }] },
  { slug: "jeevan-pramaan", categorySlug: "government-services", title: "Jeevan Pramaan Digital Life Certificate Help", seoTitle: "Jeevan Pramaan Life Certificate in Jamshedpur", seoDescription: "Help for pensioners with the Jeevan Pramaan digital life certificate at NISE COMPORT, Kharangajhar, Telco. What to bring, how it works and follow-up.", description: "Assistance for eligible pensioners submitting a digital life certificate through the official Jeevan Pramaan process, near Kharangajhar and Telco.", keywords: ["Jeevan Pramaan Jamshedpur", "life certificate pensioner Telco", "digital life certificate Kharangajhar", "pension life certificate Jharkhand"], highlights: ["Check the pensioner's details before starting", "Guided authentication through the official Jeevan Pramaan flow", "Acknowledgement / certificate ID for your records", "Help understanding the pension-disbursing authority's follow-up"], documents: ["Aadhaar number of the pensioner (the pensioner must be present for authentication)", "Pension Payment Order (PPO) number", "Bank account details where the pension is credited", "Mobile number for the acknowledgement SMS"], steps: ["The pensioner visits with the details listed above.", "We confirm the pensioner's details and the pension-disbursing agency.", "The pensioner completes biometric or face authentication through the official process.", "Keep the acknowledgement; the pension-disbursing authority accepts and processes the certificate."], faqs: [{ question: "Must the pensioner come in person?", answer: "Yes. Authentication must be done by the pensioner through the official process. A family member cannot authenticate on their behalf." }, { question: "When is the life certificate due?", answer: "Timing depends on your pension scheme and disbursing authority; many pensioners submit it annually. Check with your bank or pension office for your deadline." }, { question: "What if authentication fails?", answer: "Fingerprints can be hard to read, especially for older pensioners. We can retry or explain other routes your pension authority accepts. Final acceptance rests with the pension-disbursing authority." }], officialLinks: [{ label: "Jeevan Pramaan (official)", href: "https://jeevanpramaan.gov.in/" }] },
  { slug: "birth-death-certificate", categorySlug: "government-services", title: "Birth & Death Certificate Application Help", seoTitle: "Birth & Death Certificate Help in Jamshedpur", seoDescription: "Help with birth and death certificate applications and corrections for Jamshedpur families. Documents to prepare and the official registration process.", description: "Guidance for families applying for, or correcting, a birth or death certificate through the official civil registration process in Jamshedpur.", keywords: ["birth certificate Jamshedpur", "death certificate Jamshedpur", "birth certificate correction Jharkhand", "CRS birth registration Telco"], highlights: ["Identify the correct registration authority and route", "Checklist for new, delayed or corrected registrations", "Form preparation and review with the family", "Acknowledgement and follow-up guidance"], documents: ["Hospital discharge slip or other proof of the birth or death event, if available", "Identity proof of the parent or informant", "Address proof", "For corrections: the existing certificate and proof of the correct detail"], steps: ["Tell us whether this is a new, delayed or corrected registration.", "We identify the registering authority and the current requirements.", "The informant reviews every detail before submission.", "Keep the acknowledgement and follow up with the registrar's office."], faqs: [{ question: "Is late registration possible?", answer: "Delayed registration is possible, but it usually needs additional documents or orders, depending on the delay. The registrar decides what is required." }, { question: "Can you issue the certificate?", answer: "No. Certificates are issued by the registrar of births and deaths. We help you prepare and submit the application correctly." }], officialLinks: [{ label: "Civil Registration System (Office of the Registrar General)", href: "https://crsorgi.gov.in/" }] },
  { slug: "land-mutation", categorySlug: "government-services", title: "Land Mutation (Dakhil-Kharij) & Jharbhoomi Help", seoTitle: "Land Mutation & Jharbhoomi Help in Jamshedpur", seoDescription: "Help with online land mutation (dakhil-kharij) applications and Jharbhoomi land-record look-ups in Jharkhand. Documents to prepare and status follow-up.", description: "Assistance with online mutation (dakhil-kharij) applications, land-record look-ups and status checks through Jharkhand's official Jharbhoomi portal.", keywords: ["land mutation Jamshedpur", "dakhil kharij Jharkhand", "Jharbhoomi help Telco", "online mutation Jharkhand", "khatiyan Jamshedpur"], highlights: ["Online mutation application preparation", "Land-record (register-II, khatiyan) look-up guidance", "Document checklist review before submission", "Application status follow-up on the official portal"], documents: ["Registered sale deed, gift deed or other transfer document", "Identity proof of the applicant", "Previous rent receipt or land-record details where available", "Details of the plot (khata, plot number, mouza/village)"], steps: ["Share the transfer document and plot details.", "We check what the official portal asks for your type of transfer.", "You review the application before it is submitted online.", "Track the application; the circle office carries out verification and decides."], faqs: [{ question: "How long does mutation take?", answer: "The circle office and revenue authority control verification and timelines. We cannot promise a date." }, { question: "Is this legal advice?", answer: "No. We help with the online application. For disputes or unclear titles, consult a qualified advocate." }], officialLinks: [{ label: "Jharbhoomi – Jharkhand land records", href: "https://jharbhoomi.jharkhand.gov.in/" }] },
  { slug: "aadhaar-pvc-card", categorySlug: "government-services", title: "Aadhaar PVC Card Order Help", seoTitle: "Aadhaar PVC Card Order Help in Jamshedpur", seoDescription: "Help ordering the official Aadhaar PVC card through UIDAI's myAadhaar service, tracking delivery, and avoiding unofficial PVC printouts.", description: "Help ordering the official Aadhaar PVC card from UIDAI, checking the delivery address and tracking the order, near Kharangajhar and Telco.", keywords: ["Aadhaar PVC card Jamshedpur", "order Aadhaar PVC card", "Aadhaar card print Telco", "PVC Aadhaar Kharangajhar"], highlights: ["Order through UIDAI's official myAadhaar service", "Check the address the card will be posted to", "Payment only through the official UIDAI page", "Order tracking with the SRN"], documents: ["Aadhaar number", "Mobile phone that receives the Aadhaar OTP (the holder enters the OTP personally)"], steps: ["Confirm the address on your Aadhaar is correct; the card is posted there.", "Place the order on UIDAI's official page and pay the fee shown there.", "Save the Service Request Number (SRN).", "Track the order and the postal delivery until the card arrives."], faqs: [{ question: "Is a shop-printed PVC card the same?", answer: "No. The official Aadhaar PVC card is printed and posted by UIDAI. Cards printed elsewhere are not the official PVC card." }, { question: "My address is old. What should I do?", answer: "Update your address first, then order the PVC card, because the card goes to the address on record." }], officialLinks: [{ label: "myAadhaar (UIDAI)", href: "https://myaadhaar.uidai.gov.in/" }] },
  { slug: "bank-account-opening", categorySlug: "banking", title: "Bank Account Opening Assistance (BC Point)", seoTitle: "Bank Account Opening Help in Telco, Jamshedpur", seoDescription: "Ask about opening a basic savings account through our banking correspondent point in Kharangajhar, Telco. Documents, KYC and next steps.", description: "Ask about opening an eligible basic savings account through the partner bank's Business Correspondent (BC) channel at our Telco service desk.", keywords: ["bank account opening Jamshedpur", "Jan Dhan account Telco", "BC point Kharangajhar", "zero balance account Jamshedpur"], highlights: ["Check which account types the partner bank currently offers", "KYC document checklist", "Account-opening form support through the bank's channel", "Guidance on activating and using the account safely"], documents: ["Aadhaar and other KYC documents the bank asks for", "Recent photograph if requested", "Mobile number for account alerts"], steps: ["Ask which account types are available through the BC channel today.", "Bring the KYC documents the bank lists.", "Complete verification yourself; never share your PIN or OTP.", "The bank opens the account after its own checks."], faqs: [{ question: "Does NISE COMPORT open the account?", answer: "No. The partner bank opens and runs the account. We help with the process as its Business Correspondent point, where available." }, { question: "Is there a minimum balance?", answer: "Rules differ by account type and are set by the bank. We explain the bank's current terms before you apply." }] },
  { slug: "ayushman-card", categorySlug: "government-services", title: "Ayushman Card (PM-JAY) & ABHA Health ID Help", seoTitle: "Ayushman Card & ABHA Help in Telco, Jamshedpur", seoDescription: "Check Ayushman Bharat (PM-JAY) eligibility, make or download the Ayushman card and create an ABHA health ID with local help in Kharangajhar, Telco.", description: "Local help checking Ayushman Bharat (PM-JAY) eligibility, making or downloading the Ayushman card, and creating an ABHA health ID with Aadhaar verification.", keywords: ["Ayushman card Jamshedpur", "PM-JAY card Telco", "ABHA card Kharangajhar", "Ayushman card for 70 plus Jamshedpur"], highlights: ["Eligibility check for the family", "Ayushman card creation and download", "Cards for senior citizens aged 70 and above", "ABHA (health account) creation"], documents: ["Aadhaar card of each family member", "Mobile number linked to Aadhaar for the OTP", "Ration card or the PM/CM letter for the family", "Income or caste certificate only if asked"], steps: ["Tell us who needs the card; we check the family's eligibility first.", "The card holder completes Aadhaar OTP or fingerprint verification at the counter.", "We submit the card request and tell you when it is approved.", "Collect the printed card or keep the digital copy on your phone."], faqs: [{ question: "Who can get an Ayushman card?", answer: "Families on the eligibility list, and every person aged 70 or more regardless of income. We check the list for you before starting." }, { question: "Can I get the card the same day?", answer: "If the family is already eligible and verification works, the card is often ready quickly. Some cards need approval, which can take a few days." }] },
  { slug: "ration-card", categorySlug: "government-services", title: "Ration Card Application & Correction Help", seoTitle: "Ration Card Help in Telco, Jamshedpur", seoDescription: "New ration card, adding or removing members and corrections. We prepare the application and check documents at NISE COMPORT, Kharangajhar.", description: "Local help preparing a new ration card application, adding or removing family members, and correcting details on an existing card.", keywords: ["ration card Jamshedpur", "new ration card Telco", "ration card member add Jharkhand", "ration card correction Kharangajhar"], highlights: ["New ration card application", "Adding a new member (birth or marriage)", "Removing a member or correcting details", "Status updates on your application"], documents: ["Aadhaar card of every family member", "Voter ID and PAN of earning members", "Recent electricity, water or gas bill, or rent agreement", "Income certificate", "Photo and bank passbook of the head of the family (usually the eldest woman)", "Surrender or deletion certificate if you had a card elsewhere"], steps: ["Bring the documents for the whole family; we check them with you.", "We prepare and submit the application and give you the acknowledgement.", "Verification is done by the supply department.", "We tell you when the card is approved and help you download or collect it."], faqs: [{ question: "How long does a new ration card take?", answer: "It depends on the department's verification. We give you the acknowledgement number and check the status for you." }, { question: "Can I add my newborn child?", answer: "Yes. Bring the child's birth certificate, Aadhaar if made, and the existing ration card." }] },
  { slug: "abua-awas-yojana", categorySlug: "government-services", title: "Abua Awas Yojana Application Help", seoTitle: "Abua Awas Yojana Help in Jamshedpur", seoDescription: "Get your Abua Awas Yojana papers ready: Aadhaar, bank passbook, income and residence certificates. Local help at NISE COMPORT, Telco.", description: "Help preparing the documents and certificates needed for Jharkhand's Abua Awas Yojana housing scheme, including income, residence and caste certificates.", keywords: ["Abua Awas Yojana Jamshedpur", "Abua Awas form help", "Jharkhand housing scheme documents", "Abua Awas Yojana Telco"], highlights: ["Document checklist for your family", "Income, residence and caste certificates if missing", "Aadhaar-bank linking check", "Help filling the application for the block or panchayat"], documents: ["Aadhaar card", "Aadhaar-linked bank passbook", "Income certificate", "Jharkhand residence certificate", "Caste certificate, if applicable", "Ration card or BPL card", "MGNREGA job card, if you have one", "Land document for the house site, if applicable", "Passport-size photo and mobile number"], steps: ["We check which documents you have and which certificates you still need.", "We apply for any missing certificate first.", "We fill the application with you.", "You submit it at your block or panchayat camp; selection is by the government."], faqs: [{ question: "Does NISE COMPORT approve housing applications?", answer: "No. Selection and approval are done by the Jharkhand government. We help you prepare a complete application." }, { question: "What if I don't have an income certificate?", answer: "We can apply for the income certificate first. Bring an income affidavit and your identity proof." }] },
];

/** Services shown on the site. Set `published: false` on a service to hide it without deleting it. */
export const publishedServiceDetails: ServiceDetail[] = serviceDetails.filter((service) => service.published !== false);
export const allServiceItems: (ServiceGroup | ServiceDetail)[] = [...serviceCatalog, ...publishedServiceDetails];
export function findService(slug: string) { return allServiceItems.find((service) => service.slug === slug); }
export function servicesInCategory(slug: string) { return publishedServiceDetails.filter((service) => service.categorySlug === slug); }
export function categoryFor(service: ServiceDetail) { return serviceCatalog.find((group) => group.slug === service.categorySlug); }
export function isServiceDetail(service: ServiceGroup | ServiceDetail): service is ServiceDetail { return "categorySlug" in service; }

/** Shorter search titles (the tab title starts with "NISE COMPORT - Pragya Kendra - "). */
const SEO_TITLES: Record<string, string> = {
  banking: "Banking & AEPS Services in Jamshedpur",
  "form-filing": "Forms, Tax & Document Help in Jamshedpur",
  "pan-card": "PAN Card Apply & Correction in Jamshedpur",
  "aadhaar": "Aadhaar Update Help in Telco, Jamshedpur",
  "income-caste-residence-certificate": "Income, Caste & Residence Certificate Help",
  "passport-driving-licence": "Passport & Driving Licence Help, Jamshedpur",
  "aeps-money-transfer": "AEPS, Money Transfer & Banking in Telco",
  "bike-insurance": "Bike Insurance Renewal Help in Jamshedpur",
  "car-insurance": "Car Insurance Renewal Help in Jamshedpur",
  "health-life-insurance": "Health & Life Insurance Help in Jamshedpur",
  "scholarship-forms": "Scholarship & Admission Form Help, Jamshedpur",
  "exam-forms": "Online Exam & Job Form Filling in Jamshedpur",
  "bill-payment-recharge": "Bill Payment & Recharge in Telco, Jamshedpur",
  "itr-gst": "ITR & GST Form Help in Jamshedpur",
  "printing-scanning": "Online Printing & Photocopy in Jamshedpur",
  "computer-repair": "Computer, Printer & CCTV Service, Jamshedpur",
  "website-design": "Business Website & Digital Help, Jamshedpur",
  "ticket-booking": "Train, Flight & Bus Ticket Booking, Jamshedpur",
  "lic-policy": "LIC Policy Service Help in Jamshedpur",
  "mutual-fund-sip": "SIP & Mutual Fund Enquiry in Jamshedpur",
  "rent-agreement": "Rent Agreement & NOC Help in Jamshedpur",
  "fssai-license": "FSSAI Food Licence Registration, Jamshedpur",
  "udyam-registration": "Udyam MSME Registration Help, Jamshedpur",
};

/** Search-result title for a service page, without repeating "in Jamshedpur". */
export function serviceSeoTitle(service: ServiceGroup | ServiceDetail) {
  if (isServiceDetail(service) && service.seoTitle) return service.seoTitle;
  if (SEO_TITLES[service.slug]) return SEO_TITLES[service.slug];
  return /jamshedpur/i.test(service.title) ? service.title : `${service.title} in Jamshedpur`;
}

function trimAtWord(text: string, max: number) {
  if (text.length <= max) return text;
  const cut = text.slice(0, max - 1);
  return `${cut.slice(0, cut.lastIndexOf(" ")).replace(/[,;:.\s]+$/, "")}…`;
}

export function serviceSeoDescription(service: ServiceGroup | ServiceDetail) {
  if (isServiceDetail(service) && service.seoDescription) return service.seoDescription;
  const suffix = " NISE COMPORT, Kharangajhar, Telco, Jamshedpur.";
  const base = service.description.trim();
  return base.length + suffix.length <= 160 ? base + suffix : trimAtWord(base, 160);
}

/** Where "Start request" goes for a service: PAN and printing have their own step flows. */
export function requestHrefFor(slug: string) {
  if (slug === "pan-card") return "/pan/request";
  if (slug === "printing-scanning") return "/print";
  if (serviceCatalog.some((group) => group.slug === slug)) return `/request?category=${encodeURIComponent(slug)}`;
  return `/request?service=${encodeURIComponent(slug)}`;
}

/** Short, card-friendly name: drops the trailing location and "Assistance"/"Help" filler. */
export function shortServiceName(title: string) {
  return title.replace(/\s+(in|near)\s+(Jamshedpur|Telco)(,.*)?$/i, "").replace(/\s+\((BC Point)\)$/i, "").replace(/\s+(Assistance|Help)$/i, "").trim();
}
