export const serviceCatalog = [
  { slug:"government-services",title:"Government & citizen services",description:"Get local guidance with PAN applications and corrections, selected Aadhaar updates, voter enrolment, passport forms and e-district services.",keywords:["PAN card Jamshedpur","Aadhaar update Kharangajhar","voter ID help Jamshedpur","income caste residence certificate"] },
  { slug:"banking",title:"Banking & Business Correspondent services",description:"Access assisted banking and payment services through our local service desk, including account support, transfers and withdrawals where available.",keywords:["banking services Kharangajhar","money transfer Jamshedpur","CSC banking support"] },
  { slug:"insurance",title:"Insurance assistance",description:"Get help understanding and applying for motor, life and general insurance products through participating providers.",keywords:["bike insurance Jamshedpur","car insurance Kharangajhar","insurance help Jharkhand"] },
  { slug:"education",title:"Education & student services",description:"Get support with school, college, university, exam, scholarship and other education related applications.",keywords:["online form filling Jamshedpur","student services Kharangajhar","scholarship application help"] },
  { slug:"fee-payments",title:"Fee payments & bill payments",description:"Get help making selected online fee, utility and other bill payments, with confirmation and receipts where available.",keywords:["online bill payment Jamshedpur","fee payment Kharangajhar"] },
  { slug:"form-filing",title:"Form filing & document assistance",description:"Get careful help with application forms, document uploads, payment steps and receipt collection.",keywords:["form filling Jamshedpur","ITR form assistance Jharkhand","online applications Kharangajhar"] },
  { slug:"it-services",title:"IT, printing & document services",description:"Printing, scanning and digital document services, plus website and technology help for local businesses.",keywords:["printing Kharangajhar","document scan Jamshedpur","website services Jharkhand"] },
  { slug:"travel",title:"Travel & ticket support",description:"Get assistance with selected travel bookings and ticket related online services.",keywords:["ticket booking Jamshedpur","travel services Kharangajhar"] },
];
