import type {Metadata} from "next";
import Link from "next/link";
import {notFound} from "next/navigation";
import {ArrowLeft,ArrowRight,Check,MapPin,ShieldCheck} from "lucide-react";
import {serviceCatalog} from "@/lib/services";
import {pageMetadata} from "@/lib/seo";
import RequestServiceForm from "@/components/request-service-form";
export function generateStaticParams(){return serviceCatalog.map(service=>({slug:service.slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const service=serviceCatalog.find(item=>item.slug===slug);if(!service)return {};return {...pageMetadata(`${service.title} in Jamshedpur`,`${service.description} NISE COMPORT offers local assistance in Kharangajhar, Jamshedpur.`, `/services/${service.slug}`),keywords:[...service.keywords,"NISE COMPORT","Jamshedpur","Kharangajhar","Jharkhand"]}}
export default async function ServiceDetail({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const service=serviceCatalog.find(item=>item.slug===slug);if(!service)notFound();return <main className="content-page"><header className="content-nav"><div className="container content-nav-inner"><Link className="brand" href="/"><span className="brand-mark">N</span><span>NISE <b>COMPORT</b><small>YOUR DIGITAL SERVICE DESK</small></span></Link><Link className="button button-dark" href="/services">All services <ArrowRight size={14}/></Link></div></header><section className="content-hero detail-hero"><div className="container"><Link href="/services" className="back-small"><ArrowLeft size={14}/> All services</Link><span className="eyebrow eyebrow-muted">LOCAL HELP · KHARANGAJHAR, JAMSHEDPUR</span><h1>{service.title.split(" & ")[0]}<br/><em>{service.title.includes(" & ")?`& ${service.title.split(" & ").slice(1).join(" & ")}`:"support, made simpler."}</em></h1><p>{service.description}</p><Link className="button button-green" href="/signup">Start a request <ArrowRight size={15}/></Link></div></section><section className="container detail-body"><div><h2>How we can help</h2><p>Our team can guide you through the relevant online process, help organize required documents and explain the steps involved. Bring accurate information and original documents where the portal or authority requires them.</p><ul>{["Understand the application steps and document checklist","Get help with form entry and document upload","Review details before submission and keep your receipt","Follow up using the reference or acknowledgement number"].map(item=><li key={item}><Check size={15}/>{item}</li>)}</ul></div><aside><span><MapPin size={17}/></span><h3>Visit your local service desk</h3><p>Kharangajhar, Jamshedpur, Jharkhand</p><Link href="/contact">Contact us <ArrowRight size={14}/></Link></aside></section><section className="container request-section-wrap"><RequestServiceForm slug={service.slug} title={service.title}/></section><section className="container provider-note"><ShieldCheck size={18}/><p>We are an independent CSC / Pragya Kendra service provider, not a government authority. Our service fee is separate from any government or third-party fee. The applicant is responsible for accurate information. Approval, processing time and decisions rest with the relevant authority; completed service charges are generally non-refundable.</p></section></main>}
