import type { Metadata } from "next";
import Link from "next/link";
import SiteHeader from "@/components/site-header";
import Breadcrumbs from "@/components/breadcrumbs";
import JsonLd from "@/components/json-ld";
import { pageMetadata } from "@/lib/seo";
import { itemListLd } from "@/lib/structured-data";
import { panGuides } from "@/lib/pan-content";
import { panServices,panServiceLabels } from "@/lib/pan-validation";
export const metadata:Metadata=pageMetadata("PAN Card Help Centre: Apply, Correct, Track","PAN help in Kharangajhar, Telco, Jamshedpur: new PAN, corrections, reprints, minor and business PAN, Aadhaar linking, e-PAN and official tracking links.","/pan",{image:"/og/services/pan-card-jamshedpur.png"});
export default function PanHub(){return <main><SiteHeader/><div className="container pan-page"><Breadcrumbs items={[{name:"Home",path:"/"},{name:"PAN help",path:"/pan"}]}/><JsonLd data={itemListLd("PAN guides",panGuides.map(g=>({name:g.title,path:`/pan/${g.slug}`})))}/><header className="pan-hero"><span className="eyebrow">NISE COMPORT · JAMSHEDPUR</span><h1>Your PAN questions,<br/>clear next steps.</h1><p>Start with what you need. Read the checklist, prepare your information and send a private assistance request to our Kharangajhar service desk.</p><Link className="button button-green" href="/pan/request">Start a PAN assistance request</Link> <Link className="button button-outline" href="/pan/status">Track an official application</Link></header><section><h2>What would you like help with?</h2><div className="pan-grid">{panServices.map(service=><Link className="pan-card" href={`/pan/request?type=${service}`} key={service}><h3>{panServiceLabels[service]}</h3><p>Check the route and prepare a request →</p></Link>)}</div></section><section><h2>Your PAN information hub</h2><div className="pan-grid">{panGuides.map(guide=><Link className="pan-card" key={guide.slug} href={`/pan/${guide.slug}`}><h3>{guide.title}</h3><p>{guide.intro}</p><span>Read guide →</span></Link>)}</div></section><aside className="pan-card"><h2>Before you begin</h2><p>Already have a PAN? Choose correction or reprint instead of requesting another PAN. Fees, evidence and processing depend on the provider and application category. NISE COMPORT confirms its assistance charge separately before proceeding.</p><p>We provide independent local guidance. The Income Tax Department and its providers control official processing and approval.</p></aside></div></main>;}
