import type { Metadata } from "next";
import { redirect } from "next/navigation";
import { desc, eq } from "drizzle-orm";
import ProfileDashboard from "@/components/profile-dashboard";
import DemoProfile from "@/components/demo-profile";
import { getCurrentUser } from "@/lib/auth";
import { db } from "@/lib/db";
import { printJobs, serviceRequests, walletEntries } from "@/db/schema";
export const metadata: Metadata = { title:"Customer profile", robots:{index:false,follow:false} };
export default async function ProfilePage(){const user=await getCurrentUser();if(!user)redirect("/login?next=/profile");if(user.role==="demo")return <DemoProfile/>;const [requests,jobs,wallet]=await Promise.all([db.select({id:serviceRequests.id,reference:serviceRequests.reference,serviceSlug:serviceRequests.serviceSlug,serviceName:serviceRequests.serviceName,status:serviceRequests.status,details:serviceRequests.details,createdAt:serviceRequests.createdAt}).from(serviceRequests).where(eq(serviceRequests.userId,user.id)).orderBy(desc(serviceRequests.createdAt)).limit(50),db.select({id:printJobs.id,reference:printJobs.reference,status:printJobs.status,total:printJobs.total,fulfillment:printJobs.fulfillment,createdAt:printJobs.createdAt}).from(printJobs).where(eq(printJobs.userId,user.id)).orderBy(desc(printJobs.createdAt)).limit(50),db.select({id:walletEntries.id,amount:walletEntries.amount,kind:walletEntries.kind,description:walletEntries.description,reference:walletEntries.reference,createdAt:walletEntries.createdAt}).from(walletEntries).where(eq(walletEntries.userId,user.id)).orderBy(desc(walletEntries.createdAt)).limit(50)]);const safeDetails=requests.map(({details,...request})=>({...request,description:typeof details==="object"&&details!==null&&"description" in details&&typeof details.description==="string"?details.description:"",createdAt:request.createdAt.toISOString()}));return <ProfileDashboard user={{id:user.id,name:user.name,email:user.email,phone:user.phone}} initialRequests={safeDetails} initialJobs={jobs.map(job=>({...job,createdAt:job.createdAt.toISOString()}))} initialWallet={wallet.map(entry=>({...entry,createdAt:entry.createdAt.toISOString()}))}/>}
