import { test } from 'node:test';
import assert from 'node:assert/strict';
import { panIntakeSchema,validPastDate,ageOnDate,panFormFor,validateTracking } from '../src/lib/pan-validation.ts';
const valid={service:'new',citizenship:'indian',applicant:'individual',residency:'india',existingPan:'no',fullName:'Test Applicant',birthDate:'1996-02-29',contactName:'Test Customer',email:'test@example.com',phone:'+919876543210',address:'Test street 10',city:'Jamshedpur',state:'Jharkhand',country:'India',postalCode:'831004',consent:true};
test('valid common request; impossible and future dates rejected',()=>{assert.ok(panIntakeSchema.safeParse(valid).success);assert.equal(validPastDate('2025-02-29'),false);assert.equal(validPastDate('2099-01-01'),false);assert.equal(ageOnDate('2008-09-28','2026-09-27'),17);assert.equal(ageOnDate('2008-09-28','2026-09-28'),18);});
test('duplicate new PAN, missing consent and incorrect PIN rejected',()=>{for(const patch of [{existingPan:'yes'},{existingPan:'unsure'},{consent:false},{postalCode:'000000'},{phone:'abcd'},{email:'invalid'}])assert.equal(panIntakeSchema.safeParse({...valid,...patch}).success,false);});
test('corrections require selected changes and an existing PAN',()=>{assert.equal(panIntakeSchema.safeParse({...valid,service:'correction',existingPan:'yes'}).success,false);assert.ok(panIntakeSchema.safeParse({...valid,service:'correction',existingPan:'yes',corrections:['name']}).success);});
test('entity requires entity type and representative; minor requires guardian',()=>{assert.equal(panIntakeSchema.safeParse({...valid,service:'business',applicant:'entity'}).success,false);assert.ok(panIntakeSchema.safeParse({...valid,service:'business',applicant:'entity',entityType:'firm',representative:'Test Representative'}).success);assert.equal(panIntakeSchema.safeParse({...valid,service:'minor',birthDate:'2015-01-01'}).success,false);assert.ok(panIntakeSchema.safeParse({...valid,service:'minor',birthDate:'2015-01-01',representative:'Test Guardian'}).success);});
test('form category follows citizenship, tracking only validates format',()=>{assert.equal(panFormFor({citizenship:'indian',applicant:'individual'}),'Form 93');assert.equal(panFormFor({citizenship:'foreign',applicant:'entity'}),'Form 96');assert.equal(validateTracking('protean','123456789012345'),'');assert.notEqual(validateTracking('protean','N-12345'),'');assert.notEqual(validateTracking('uti','<script>'),'');assert.notEqual(validateTracking('unknown','123456789012345'),'');});
