import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import SiteHeader from "@/components/site-header";
import { PanIssueSearch,PanStatusTool } from "@/components/pan-tools";
import { panGuides } from "@/lib/pan-content";
export function generateStaticParams(){return panGuides.map(g=>({topic:g.slug}));}
export async function generateMetadata({params}:{params:Promise<{topic:string}>}):Promise<Metadata>{const {topic}=await params;const guide=panGuides.find(g=>g.slug===topic);return {title:guide?`${guide.title} | NISE COMPORT Jamshedpur`:"PAN guide",description:guide?.intro,alternates:{canonical:`/pan/${topic}`}};}
export default async function Guide({params}:{params:Promise<{topic:string}>}){const {topic}=await params;const guide=panGuides.find(g=>g.slug===topic);if(!guide)notFound();return <main><SiteHeader/><div className="container pan-page"><nav aria-label="Breadcrumb"><Link href="/">Home</Link> / <Link href="/pan">PAN help</Link> / {guide.title}</nav><header className="pan-hero"><h1>{guide.title}</h1><p>{guide.intro}</p></header><nav className="pan-tabs" aria-label="PAN topics">{panGuides.map(g=><Link aria-current={g.slug===topic?"page":undefined} key={g.slug} href={`/pan/${g.slug}`}>{g.slug.replaceAll("-"," ")}</Link>)}</nav>{topic==="status"&&<PanStatusTool/>}{guide.sections.map(section=><section className="pan-card" key={section.title}><h2>{section.title}</h2><ul>{section.points.map(point=><li key={point}>{point}</li>)}</ul></section>)}{topic==="issues"&&<PanIssueSearch/>}<section><h2>Frequently asked questions</h2>{guide.faqs.map(f=><details className="pan-card" key={f.q}><summary>{f.q}</summary><p>{f.a}</p></details>)}</section><aside className="pan-card"><h2>Official sources and next steps</h2><p>Reviewed 28 September 2026. Verify requirements on the selected provider before submission.</p><ul>{guide.links.map(link=><li key={link.href}><a href={link.href} target="_blank" rel="noreferrer">{link.label} ↗</a></li>)}</ul><Link className="button button-green" href="/pan/request">Ask NISE COMPORT for assistance</Link><p>Independent local assistance. Government processing and approval are handled by the relevant authority; this guide does not guarantee approval or delivery dates.</p></aside></div></main>;}
