import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import SiteHeader from "@/components/site-header";
import { PanIssueSearch,PanStatusTool } from "@/components/pan-tools";
import { panGuides } from "@/lib/pan-content";
import JsonLd from "@/components/json-ld";
import { pageMetadata } from "@/lib/seo";
import { breadcrumbLd, faqLd } from "@/lib/structured-data";
export function generateStaticParams(){return panGuides.map(g=>({topic:g.slug}));}
export const dynamicParams=false;
const PAN_SEO_TITLES:Record<string,string>={application:"Apply for a New PAN Card in Jamshedpur",correction:"PAN Card Correction & Name Change Help",["aadhaar-linking"]:"Link PAN with Aadhaar: Status & Steps",status:"Track PAN Card Application Status",epan:"Instant e-PAN & e-PAN Download Help",forms:"PAN Forms 93–96 & Document Checklist",reprint:"Lost or Damaged PAN Card Reprint",issues:"PAN Card Problems & How to Fix Them"};
export async function generateMetadata({params}:{params:Promise<{topic:string}>}):Promise<Metadata>{const {topic}=await params;const guide=panGuides.find(g=>g.slug===topic);if(!guide)return {};return pageMetadata(PAN_SEO_TITLES[guide.slug]??`${guide.title} – PAN Help`,guide.intro.length>160?guide.intro.slice(0,157).replace(/\s+\S*$/,"")+"…":guide.intro,`/pan/${guide.slug}`,{image:"/og/services/pan-card-jamshedpur.png"});}
export default async function Guide({params}:{params:Promise<{topic:string}>}){const {topic}=await params;const guide=panGuides.find(g=>g.slug===topic);if(!guide)notFound();return <main><SiteHeader/><div className="container pan-page"><JsonLd data={[breadcrumbLd([{name:"Home",path:"/"},{name:"PAN help",path:"/pan"},{name:guide.title,path:`/pan/${guide.slug}`}]),faqLd(guide.faqs.map(f=>({question:f.q,answer:f.a})))]}/><nav aria-label="Breadcrumb"><Link href="/">Home</Link> / <Link href="/pan">PAN help</Link> / {guide.title}</nav><header className="pan-hero"><h1>{guide.title}</h1><p>{guide.intro}</p></header><nav className="pan-tabs" aria-label="PAN topics">{panGuides.map(g=><Link aria-current={g.slug===topic?"page":undefined} key={g.slug} href={`/pan/${g.slug}`}>{g.slug.replaceAll("-"," ")}</Link>)}</nav>{topic==="status"&&<PanStatusTool/>}{guide.sections.map(section=><section className="pan-card" key={section.title}><h2>{section.title}</h2><ul>{section.points.map(point=><li key={point}>{point}</li>)}</ul></section>)}{topic==="issues"&&<PanIssueSearch/>}<section><h2>Frequently asked questions</h2>{guide.faqs.map(f=><details className="pan-card" key={f.q}><summary>{f.q}</summary><p>{f.a}</p></details>)}</section><aside className="pan-card"><h2>Official sources and next steps</h2><p>Reviewed 28 September 2026. Verify requirements on the selected provider before submission.</p><ul>{guide.links.map(link=><li key={link.href}><a href={link.href} target="_blank" rel="noreferrer">{link.label} ↗</a></li>)}</ul><Link className="button button-green" href="/pan/request">Ask NISE COMPORT for assistance</Link><p>Independent local assistance. Government processing and approval are handled by the relevant authority; this guide does not guarantee approval or delivery dates.</p></aside></div></main>;}
