import SiteHeader from "@/components/site-header";
import type { Metadata } from "next";
import Link from "next/link";
import Image from "next/image";
import { notFound } from "next/navigation";
import { ArrowLeft, ArrowUpRight, Check } from "lucide-react";
import { articles } from "@/lib/content";
import { pageMetadata } from "@/lib/seo";
export function generateStaticParams() { return articles.map(item=>({slug:item.slug})); }
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const item=articles.find(article=>article.slug===slug);return item?pageMetadata(item.title,item.excerpt,`/blog/${item.slug}`):{};}
export default async function ArticlePage({params}:{params:Promise<{slug:string}>}) { const {slug}=await params;const item=articles.find(article=>article.slug===slug);if(!item)notFound();return <main className="content-page"><SiteHeader/><article className="container article-page"><Link className="back-small" href="/blog"><ArrowLeft size={14}/> All local guides</Link><span className="eyebrow eyebrow-muted">{item.category.toUpperCase()} · JAMSHEDPUR</span><h1>{item.title}</h1><p className="article-excerpt">{item.excerpt}</p><Image className="article-cover" src={item.image} alt="" width={1200} height={720} priority/><div className="article-layout"><div>{item.paragraphs?.map((paragraph,index)=><p key={index}>{paragraph}</p>) ?? <p>Jeevan Pramaan is a digital life-certificate service for eligible pensioners. Check current official instructions and supported submission methods before visiting. Bring only the information and documents requested by the authorised flow, complete required identity verification yourself and retain the acknowledgement for your pension authority. NISE COMPORT can provide navigation assistance where available; the pension-disbursing authority sets acceptance and processing rules.</p>}<h2>Before you start</h2><ul>{item.checklist?.map(point=><li key={point}><Check size={16}/>{point}</li>) ?? ["Check current official instructions", "Keep the acknowledgement for follow-up", "Confirm whether an authorised biometric step is required"].map(point=><li key={point}><Check size={16}/>{point}</li>)}</ul><p className="article-disclaimer">Requirements can change. The responsible government department, insurer, institution or service provider decides eligibility, fees, processing and final outcomes.</p></div><aside><strong>Need help with this service?</strong><p>Talk to the NISE COMPORT team in Kharangajhar, Telco, Jamshedpur.</p><Link className="button button-green" href={`/services/${item.serviceSlug}`}>View service <ArrowUpRight size={15}/></Link><a href="https://wa.me/919771219893" className="article-whatsapp">Ask on WhatsApp</a></aside></div></article></main>; }
