import SiteHeader from "@/components/site-header";
import Link from "next/link";
import Image from "next/image";
import type { Metadata } from "next";
import { galleryItems, socialPosts, articles } from "@/lib/content";
import { ArrowRight, ArrowUpRight, BadgeCheck, Banknote, BookOpenCheck, Check, ChevronRight, Clock3, FileText, Fingerprint, HeartHandshake, Landmark, MapPin, Phone, Printer, ShieldCheck, Sparkles, WalletCards } from "lucide-react";
import FaqSection from "@/components/faq-section";
import JsonLd from "@/components/json-ld";
import OpenStatus from "@/components/open-status";
import { summarizeHours } from "@/lib/hours";
import { pageMetadata } from "@/lib/seo";
import { site, whatsappLink } from "@/lib/site";
import { webPageLd } from "@/lib/structured-data";

export const metadata: Metadata = {
  ...pageMetadata(
    "NISE COMPORT | CSC & Pragya Kendra in Telco, Jamshedpur",
    "PAN card, Aadhaar update help, income/caste/residence certificates, AEPS banking, insurance, online forms and printing at NISE COMPORT, Kharangajhar, Telco, Jamshedpur.",
    "/",
    { languages: { "hi-IN": "/hi" }, keywords: ["CSC centre Jamshedpur", "Pragya Kendra Telco", "Pragya Kendra Kharangajhar", "PAN card Jamshedpur", "Aadhaar update Jamshedpur", "income certificate Jamshedpur", "caste certificate Jharkhand", "AEPS Telco", "online form filling Jamshedpur", "printing Telco", "प्रज्ञा केंद्र जमशेदपुर", "सीएससी सेंटर टेल्को"] },
  ),
};

const services = [
  { icon: Fingerprint, title: "PAN & Aadhaar", text: "New PAN, corrections and reprints; guidance on the right Aadhaar update route.", tag: "Identity", href: "/services/pan-card-jamshedpur", links: [{ href: "/services/pan-card-jamshedpur", label: "PAN card" }, { href: "/services/aadhaar-assistance-jamshedpur", label: "Aadhaar update help" }] },
  { icon: Landmark, title: "Certificates & forms", text: "Income, caste, residence, EWS, birth and voter services through official portals.", tag: "Government", href: "/services/jharkhand-certificates-jamshedpur", links: [{ href: "/services/jharkhand-certificates-jamshedpur", label: "Income, caste & residence" }, { href: "/services/voter-id-services-jamshedpur", label: "Voter ID" }] },
  { icon: Banknote, title: "Banking & payments", text: "AEPS cash withdrawal, money transfer, account opening, bill payments and fee deposits.", tag: "Everyday", href: "/services/banking-aeps-money-transfer", links: [{ href: "/services/banking-aeps-money-transfer", label: "AEPS & money transfer" }, { href: "/services/fee-bill-recharge-jamshedpur", label: "Bills & recharge" }] },
  { icon: ShieldCheck, title: "Insurance", text: "Two-wheeler, car, health and life insurance enquiries through participating providers.", tag: "Protection", href: "/services/insurance", links: [{ href: "/services/bike-insurance-jamshedpur", label: "Bike insurance" }, { href: "/services/car-insurance-jamshedpur", label: "Car insurance" }] },
  { icon: Printer, title: "Print & scan", text: "Upload documents, choose exact pages, and schedule pickup or delivery.", tag: "Popular", href: "/print", links: [{ href: "/print", label: "Start a print request" }, { href: "/services/printing-scanning-jamshedpur", label: "Printing & photocopy" }] },
  { icon: BookOpenCheck, title: "Education & travel", text: "Scholarship, admission, exam and job forms; train, bus and flight booking help.", tag: "Support", href: "/services/education", links: [{ href: "/services/student-scholarship-forms-jamshedpur", label: "Scholarship forms" }, { href: "/services/exam-form-filling-jamshedpur", label: "Exam & job forms" }] },
];

const steps = ["Choose a service", "Share details securely", "Track your request", "Get it done locally"];

const homeFaqs = [
  { question: "Where is NISE COMPORT in Jamshedpur?", answer: `${site.address.oneLine}. Use the “Get directions” link on this page to open the route in Google Maps.` },
  { question: "Is NISE COMPORT a government office?", answer: "No. NISE COMPORT is an independent CSC / Pragya Kendra service centre. We help you use official and partner services; the relevant department, bank or provider makes the final decision." },
  { question: "Which services can I get here?", answer: "PAN card applications and corrections, guidance on Aadhaar updates, Jharkhand income, caste, residence and EWS certificates, voter ID, AEPS banking and money transfer, insurance enquiries, scholarship and exam forms, bill payments, printing, scanning and more. See the services page for the full list." },
  { question: "Are government fees included in your charge?", answer: "No. Official or third-party fees are separate from our service charge. We explain both before any work starts and give you a receipt." },
  { question: "Do I need an appointment?", answer: "No appointment is needed for most services. Sending a request online or a quick WhatsApp message helps us confirm the documents you need, so you finish in one visit." },
  { question: "Can I track my request online?", answer: "Yes. Create a free account, send a request and follow its status and reference number in your profile. We also email you when the status changes." },
];

export default function HomePage() {
  const hours = summarizeHours(site.openingHours);
  return <>
    <SiteHeader/>
    <JsonLd data={webPageLd({ name: "NISE COMPORT – CSC & Pragya Kendra in Telco, Jamshedpur", description: site.description, path: "/" })}/>
    <main>
      <section className="hero"><div className="container hero-grid"><div className="hero-copy"><div className="eyebrow"><span className="eyebrow-dot"/> CSC · PRAGYA KENDRA · KHARANGAJHAR, TELCO <span className="eyebrow-line"/></div><h1>Your CSC &amp; Pragya Kendra in <em>Telco, Jamshedpur.</em></h1><p className="hero-lead">Less paperwork, more progress. Get in-person help with PAN, Aadhaar updates, Jharkhand certificates, banking, insurance, online forms and printing, with clear fees and next steps.</p><div className="hero-buttons"><Link href="/services" className="button button-green">Explore our services <ArrowRight size={17}/></Link><a href={`tel:${site.phones.primary.e164}`} className="text-link"><Phone size={15}/> {site.phones.primary.display}</a><a href="#how-it-works" className="text-link">How it works <ChevronRight size={16}/></a></div><div className="hero-proof"><div className="avatar-stack"><span>NC</span><span>IN</span><span>✓</span></div><div><strong>Here when you need us</strong><small>Hanuman Mandir Road, Kharangajhar, Telco</small></div><div className="proof-divider"/><div className="proof-stars"><OpenStatus rules={site.openingHours}/><small>{hours.length ? hours[0] : "Mon–Sat · Walk in or call first"}</small></div></div></div>
        <div className="hero-visual"><div className="visual-orbit orbit-one"/><div className="visual-orbit orbit-two"/><div className="hero-photo"><div className="photo-caption"><span className="caption-icon"><MapPin size={16}/></span><div><strong>Your neighbourhood service desk</strong><small>Kharangajhar · Telco · Jamshedpur</small></div></div></div><div className="floating-card status-card"><span className="status-icon"><Check size={18}/></span><div><strong>Request received</strong><small>We’ll take it from here</small></div><span className="status-pulse"/></div><div className="floating-card trust-card"><div className="trust-icon"><ShieldCheck size={19}/></div><div><strong>Your details, respected</strong><small>Handled with care at every step</small></div></div><div className="hero-stamp"><Sparkles size={16}/><span>HERE TO<br/>HELP</span></div></div>
      </div><div className="container hero-bottom"><span>ONE COUNTER, MANY SOLUTIONS</span><div className="hero-bottom-line"/><span>{hours.length ? hours.join(" · ") : <>Mon–Sat <b>·</b> Personal assistance available</>}</span></div></section>
      <section className="service-section section-pad" id="services"><div className="container"><div className="section-heading"><div><div className="eyebrow eyebrow-muted">SERVICES MADE SIMPLE</div><h2>Help for the things<br/>that <em>move you forward.</em></h2></div><div className="section-heading-side"><p>From PAN and certificates to AEPS banking and printing: dependable help in Kharangajhar, Telco, without the runaround.</p><Link className="arrow-link" href="/services">See all services <ArrowUpRight size={16}/></Link></div></div><div className="service-grid">{services.map(({ icon: Icon, title, text, tag, href, links }, i) => <article className="service-card" key={title}><div className="service-card-top"><span className="service-icon"><Icon size={20} strokeWidth={1.8}/></span><span className="service-num">0{i + 1}</span></div><div className="service-tag">{tag}</div><h3><Link href={href}>{title}</Link></h3><p>{text}</p><div className="service-card-links">{links.map((link) => <Link key={link.href} href={link.href}>{link.label}</Link>)}</div><Link href={href} aria-label={`Explore ${title}`} className="card-arrow"><ArrowUpRight size={17}/></Link></article>)}</div><div className="service-note"><span className="note-check"><Check size={15}/></span><p>We’re an independent service centre helping you navigate digital and government portals. <Link href="/about">Learn about our role</Link></p></div></div></section>
      <section className="process-section section-pad" id="how-it-works"><div className="container process-layout"><div className="process-intro"><div className="eyebrow eyebrow-light">A CLEARER WAY TO GET THINGS DONE</div><h2>Four steps.<br/><em>Real support.</em></h2><p>No confusing process. We’ll guide you from your first question to the final receipt.</p><Link href="/services" className="button button-cream">Start with a service <ArrowRight size={16}/></Link></div><div className="process-steps">{steps.map((step, index) => <div className="process-step" key={step}><span className="step-number">0{index + 1}</span><div><h3>{step}</h3><p>{["Browse the options or tell us what you need.", "We’ll explain documents, service fees and next steps.", "Check progress and updates in your customer profile.", "Collect your documents or choose a convenient delivery."][index]}</p></div><span className="step-check"><Check size={15}/></span></div>)}</div></div></section>
      <section className="print-feature section-pad"><div className="container print-layout"><div className="print-visual"><div className="paper-sheet"><div className="paper-top"><span>N</span><span>DOCUMENT SERVICES</span></div><div className="paper-lines"><i/><i/><i/><i/><i/></div><div className="paper-highlight"><span>PAGE 01</span><b>B&amp;W</b></div><div className="paper-lines short"><i/><i/><i/></div><div className="paper-footer">NISE COMPORT · PRINT JOB</div></div><div className="print-bubble"><Printer size={18}/><span>Ready for<br/><b>pickup</b></span></div><div className="print-seal"><Check size={18}/></div></div><div className="print-copy"><div className="eyebrow eyebrow-muted">ONLINE PRINTING IN JAMSHEDPUR</div><h2>Your pages.<br/><em>Your choices.</em></h2><p>Pick pages, colour and finish, then send a request. Our team confirms the final quote and pickup or delivery; there is no online checkout.</p><div className="print-points"><span><Check size={15}/> Precise page selection</span><span><Check size={15}/> Colour or black &amp; white</span><span><Check size={15}/> Scheduled pickup or delivery</span></div><Link href="/print" className="button button-green">Request a print estimate <ArrowRight size={16}/></Link><small className="print-fine">Upload PDF, Word documents or images. Your files stay private and are removed according to our retention policy.</small></div></div></section>
      <section className="home-guides section-pad"><div className="container"><div className="section-heading"><div><div className="eyebrow eyebrow-muted">PRACTICAL LOCAL GUIDES</div><h2>Know what to bring<br/><em>before you visit.</em></h2></div><Link className="arrow-link" href="/blog">All service guides <ArrowUpRight size={16}/></Link></div><div className="guide-teasers">{articles.slice(0, 6).map(article => <article key={article.slug}><span>{article.category}</span><h3><Link href={`/blog/${article.slug}`}>{article.title}</Link></h3><p>{article.excerpt}</p><Link className="arrow-link" href={`/blog/${article.slug}`} aria-label={`Read: ${article.title}`}>Read guide <ArrowUpRight size={14}/></Link></article>)}</div></div></section>
      <section className="home-gallery section-pad"><div className="container"><div className="section-heading"><div><div className="eyebrow eyebrow-muted">FROM OUR SERVICE DESK</div><h2>Local help, made<br/><em>easy to explore.</em></h2></div><Link className="arrow-link" href="/gallery">Open the gallery <ArrowUpRight size={16}/></Link></div><div className="home-gallery-grid">{galleryItems.slice(0, 4).map(item => <Link className="home-gallery-card" href="/gallery" key={item.title}><Image src={item.image} alt={item.alt} width={520} height={350} sizes="(max-width: 700px) 50vw, 25vw"/><span>{item.category}</span><strong>{item.title}</strong></Link>)}</div></div></section>
      <section className="home-content-section"><div className="container home-content-grid"><div><div className="eyebrow eyebrow-muted">CURRENT UPDATES</div><h2>Offers, vouchers<br/><em>& social posts.</em></h2><p>Check what is active, see customer updates and ask the team before you plan around a discount.</p><div className="home-content-links"><Link href="/offers">Offers & vouchers <ArrowUpRight size={15}/></Link><Link href="/social">WhatsApp, Instagram & YouTube <ArrowUpRight size={15}/></Link></div></div><div className="home-post-grid">{socialPosts.slice(0, 2).map(post => <Link className="home-post-card" href="/social" key={post.platform}><Image src={post.image} alt={`${post.platform} update: ${post.title}`} width={360} height={230} sizes="(max-width: 700px) 50vw, 20vw"/><small>{post.platform}</small><strong>{post.title}</strong></Link>)}</div></div></section>
      <section className="about-section section-pad" id="about"><div className="container about-grid"><div className="about-art"><div className="about-image"/><div className="about-note"><HeartHandshake size={19}/><div><strong>People before process</strong><small>That’s how local service should feel.</small></div></div><div className="about-number"><strong>Local</strong><span>ROOTED IN<br/>JAMSHEDPUR</span></div></div><div className="about-copy"><div className="eyebrow eyebrow-muted">A NEIGHBOURHOOD TEAM YOU CAN REACH</div><h2>Digital services,<br/><em>with a human touch.</em></h2><p>Some things are easier when someone is there to help. We’re a local independent CSC / Pragya Kendra service centre in Kharangajhar, Telco, helping people from across Jamshedpur navigate online services with clear guidance and careful attention.</p><div className="about-promise"><span><BadgeCheck size={20}/></span><div><strong>Clear fees. Clear next steps.</strong><p>We distinguish our service charge from any government or third-party fee, and provide a receipt for the work we do.</p></div></div><Link className="arrow-link" href="/about">Get to know us <ArrowUpRight size={16}/></Link> <Link className="arrow-link" href="/areas-we-serve">Areas we serve <ArrowUpRight size={16}/></Link></div></div></section>
      <FaqSection faqs={homeFaqs} eyebrow="GOOD TO KNOW" title="Questions people ask before visiting"/>
      <section className="cta-section" id="contact"><div className="container cta-box"><div className="cta-spark"><Sparkles size={20}/></div><div><div className="eyebrow eyebrow-light">WHEN YOU NEED A HAND, WE’RE HERE</div><h2>Let’s get it <em>sorted.</em></h2><p>Call {site.phones.primary.display} or message us on WhatsApp. We’ll walk you through the next step. <br/><MapPin size={14}/> {site.address.oneLine}</p></div><div className="cta-actions"><Link href="/services" className="button button-cream">Find a service <ArrowRight size={16}/></Link><a href={whatsappLink("Hello NISE COMPORT, I need help with a service.")} className="cta-contact" target="_blank" rel="noopener noreferrer">Chat on WhatsApp <ArrowUpRight size={16}/></a><a href={site.mapsUrl} className="cta-contact" target="_blank" rel="noopener noreferrer">Get directions <ArrowUpRight size={16}/></a></div></div></section>
      <section className="trust-strip"><div className="container trust-items"><span><ShieldCheck size={17}/> Privacy-minded</span><span><WalletCards size={17}/> Transparent charges</span><span><Clock3 size={17}/> Trackable requests</span><span><MapPin size={17}/> Locally available</span></div></section>
    </main>
    <div className="mobile-dock"><Link href="/services"><Landmark size={18}/><span>Services</span></Link><Link href="/print"><Printer size={18}/><span>Print</span></Link><a href={`tel:${site.phones.primary.e164}`}><Phone size={18}/><span>Call</span></a><Link href="/profile?section=requests"><FileText size={18}/><span>Track</span></Link></div>
  </>;
}
