import Link from "next/link";
import { ArrowRight, ArrowUpRight, BadgeCheck, Banknote, BookOpenCheck, Check, ChevronRight, Clock3, FileText, Fingerprint, HeartHandshake, Landmark, MapPin, Menu, Printer, ShieldCheck, Sparkles, WalletCards } from "lucide-react";

const services = [
  { icon: Fingerprint, title: "PAN & Aadhaar", text: "New applications, corrections and selected update assistance.", tag: "Identity" },
  { icon: Landmark, title: "Certificates & forms", text: "Income, caste, residence, voter, passport and e-district support.", tag: "Government" },
  { icon: Banknote, title: "Banking & payments", text: "BC services, money transfer, bill payment and fee deposits.", tag: "Everyday" },
  { icon: ShieldCheck, title: "Insurance", text: "Compare and apply for motor, life and general insurance.", tag: "Protection" },
  { icon: Printer, title: "Print & scan", text: "Upload documents, choose exact pages, schedule pickup or delivery.", tag: "Popular" },
  { icon: BookOpenCheck, title: "Education & travel", text: "Admission and exam forms, tickets and student assistance.", tag: "Support" },
];

const steps = ["Choose a service", "Share details securely", "Track your request", "Get it done locally"];
const primaryWhatsApp = process.env.NEXT_PUBLIC_WHATSAPP_PRIMARY ?? "919771219893";

export default function HomePage() {
  return <>
    <header className="site-header"><div className="container nav-wrap"><Link className="brand" href="/" aria-label="NISE COMPORT home"><span className="brand-mark">N</span><span>NISE <b>COMPORT</b><small>YOUR DIGITAL SERVICE DESK</small></span></Link><nav className="desktop-nav"><a href="#services">Services</a><a href="#how-it-works">How it works</a><a href="#about">About us</a><a href="#contact">Contact</a></nav><div className="nav-actions"><Link className="login-link" href="/login">Sign in</Link><Link className="button button-dark nav-cta" href="/services">Explore services <ArrowUpRight size={16}/></Link><details className="mobile-nav-menu"><summary className="mobile-menu" aria-label="Open menu"><Menu size={21}/><span>Menu</span></summary><nav><a href="#services">Services</a><a href="#how-it-works">How it works</a><a href="#about">About us</a><Link href="/contact">Contact</Link><Link href="/faq">FAQs</Link></nav></details></div></div></header>
    <main>
      <section className="hero"><div className="container hero-grid"><div className="hero-copy"><div className="eyebrow"><span className="eyebrow-dot"/> YOUR LOCAL DIGITAL SERVICE DESK <span className="eyebrow-line"/></div><h1>Less paperwork.<br/><em>More progress.</em></h1><p className="hero-lead">Everyday digital services, made easier. Get thoughtful, in-person help with applications, documents, payments and more.</p><div className="hero-buttons"><Link href="/services" className="button button-green">Explore our services <ArrowRight size={17}/></Link><a href="#how-it-works" className="text-link">How it works <ChevronRight size={16}/></a></div><div className="hero-proof"><div className="avatar-stack"><span>NC</span><span>IN</span><span>✓</span></div><div><strong>Here when you need us</strong><small>Local support in Kharangajhar, Jamshedpur</small></div><div className="proof-divider"/><div className="proof-stars">★★★★★<small>People-first service</small></div></div></div>
        <div className="hero-visual"><div className="visual-orbit orbit-one"/><div className="visual-orbit orbit-two"/><div className="hero-photo"><div className="photo-caption"><span className="caption-icon"><MapPin size={16}/></span><div><strong>Your neighbourhood service desk</strong><small>Kharangajhar · Jamshedpur</small></div></div></div><div className="floating-card status-card"><span className="status-icon"><Check size={18}/></span><div><strong>Request received</strong><small>We’ll take it from here</small></div><span className="status-pulse"/></div><div className="floating-card trust-card"><div className="trust-icon"><ShieldCheck size={19}/></div><div><strong>Your details, respected</strong><small>Handled with care at every step</small></div></div><div className="hero-stamp"><Sparkles size={16}/><span>HERE TO<br/>HELP</span></div></div>
      </div><div className="container hero-bottom"><span>ONE COUNTER, MANY SOLUTIONS</span><div className="hero-bottom-line"/><span>Mon–Sat <b>·</b> Personal assistance available</span></div></section>
      <section className="service-section section-pad" id="services"><div className="container"><div className="section-heading"><div><div className="eyebrow eyebrow-muted">SERVICES MADE SIMPLE</div><h2>Help for the things<br/>that <em>move you forward.</em></h2></div><div className="section-heading-side"><p>From important applications to everyday errands, get dependable help without the runaround.</p><Link className="arrow-link" href="/services">See all services <ArrowUpRight size={16}/></Link></div></div><div className="service-grid">{services.map(({icon:Icon,title,text,tag},i)=><article className="service-card" key={title}><div className="service-card-top"><span className="service-icon"><Icon size={20} strokeWidth={1.8}/></span><span className="service-num">0{i+1}</span></div><div className="service-tag">{tag}</div><h3>{title}</h3><p>{text}</p><Link href="/services" aria-label={`Explore ${title}`} className="card-arrow"><ArrowUpRight size={17}/></Link></article>)}</div><div className="service-note"><span className="note-check"><Check size={15}/></span><p>We’re an independent service centre helping you navigate digital and government portals. <a href="#about">Learn about our role</a></p></div></div></section>
      <section className="process-section section-pad" id="how-it-works"><div className="container process-layout"><div className="process-intro"><div className="eyebrow eyebrow-light">A CLEARER WAY TO GET THINGS DONE</div><h2>Four steps.<br/><em>Real support.</em></h2><p>No confusing process. We’ll guide you from your first question to the final receipt.</p><Link href="/services" className="button button-cream">Start with a service <ArrowRight size={16}/></Link></div><div className="process-steps">{steps.map((step,index)=><div className="process-step" key={step}><span className="step-number">0{index+1}</span><div><h3>{step}</h3><p>{["Browse the options or tell us what you need.","We’ll explain documents, service fees and next steps.","Check progress and updates in your customer profile.","Collect your documents or choose a convenient delivery."][index]}</p></div><span className="step-check"><Check size={15}/></span></div>)}</div></div></section>
      <section className="print-feature section-pad"><div className="container print-layout"><div className="print-visual"><div className="paper-sheet"><div className="paper-top"><span>N</span><span>DOCUMENT SERVICES</span></div><div className="paper-lines"><i/><i/><i/><i/><i/></div><div className="paper-highlight"><span>PAGE 01</span><b>B&amp;W</b></div><div className="paper-lines short"><i/><i/><i/></div><div className="paper-footer">NISE COMPORT · PRINT JOB</div></div><div className="print-bubble"><Printer size={18}/><span>Ready for<br/><b>pickup</b></span></div><div className="print-seal"><Check size={18}/></div></div><div className="print-copy"><div className="eyebrow eyebrow-muted">A BETTER PRINT EXPERIENCE</div><h2>Your pages.<br/><em>Your choices.</em></h2><p>See a clear quote before you order. Pick the pages, colour and finish you need, then choose a pickup or delivery time that works for you.</p><div className="print-points"><span><Check size={15}/> Precise page selection</span><span><Check size={15}/> Colour or black &amp; white</span><span><Check size={15}/> Scheduled pickup or delivery</span></div><Link href="/print" className="button button-green">Start a print order <ArrowRight size={16}/></Link><small className="print-fine">Upload PDF, Word documents or images. Your files stay private and are removed according to our retention policy.</small></div></div></section>
      <section className="about-section section-pad" id="about"><div className="container about-grid"><div className="about-art"><div className="about-image"/><div className="about-note"><HeartHandshake size={19}/><div><strong>People before process</strong><small>That’s how local service should feel.</small></div></div><div className="about-number"><strong>Local</strong><span>ROOTED IN<br/>JAMSHEDPUR</span></div></div><div className="about-copy"><div className="eyebrow eyebrow-muted">A NEIGHBOURHOOD TEAM YOU CAN REACH</div><h2>Digital services,<br/><em>with a human touch.</em></h2><p>Some things are easier when someone is there to help. We’re a local independent CSC / Pragya Kendra service centre helping people navigate online services with clear guidance and careful attention.</p><div className="about-promise"><span><BadgeCheck size={20}/></span><div><strong>Clear fees. Clear next steps.</strong><p>We distinguish our service charge from any government or third-party fee, and provide a receipt for the work we do.</p></div></div><Link className="arrow-link" href="/about">Get to know us <ArrowUpRight size={16}/></Link></div></div></section>
      <section className="cta-section" id="contact"><div className="container cta-box"><div className="cta-spark"><Sparkles size={20}/></div><div><div className="eyebrow eyebrow-light">WHEN YOU NEED A HAND, WE’RE HERE</div><h2>Let’s get it <em>sorted.</em></h2><p>Tell us what you need help with. We’ll walk you through the next step.</p></div><div className="cta-actions"><Link href="/services" className="button button-cream">Find a service <ArrowRight size={16}/></Link><a href={`https://wa.me/${primaryWhatsApp}`} className="cta-contact">Chat on WhatsApp <ArrowUpRight size={16}/></a></div></div></section>
      <section className="trust-strip"><div className="container trust-items"><span><ShieldCheck size={17}/> Privacy-minded</span><span><WalletCards size={17}/> Transparent charges</span><span><Clock3 size={17}/> Trackable requests</span><span><MapPin size={17}/> Locally available</span></div></section>
    </main>
    <footer className="site-footer"><div className="container footer-main"><div className="footer-brand"><Link className="brand brand-footer" href="/"><span className="brand-mark">N</span><span>NISE <b>COMPORT</b><small>YOUR DIGITAL SERVICE DESK</small></span></Link><p>Local help for life’s digital to-dos.<br/>Serving Kharangajhar and Jamshedpur.</p></div><div className="footer-links"><strong>Explore</strong><Link href="/services">All services</Link><Link href="/print">Print &amp; scan</Link><Link href="/about">About us</Link><Link href="/contact">Contact</Link></div><div className="footer-links"><strong>Your account</strong><Link href="/login">Sign in</Link><Link href="/signup">Create an account</Link><Link href="/profile">Track a request</Link><Link href="/faq">FAQs</Link></div><div className="footer-contact"><strong>Visit or get in touch</strong><p><MapPin size={15}/> Shop No 3, Ground Floor, Singh Building,<br/>Hanuman Mandir Road, Kharangajhar, Telco,<br/>Jamshedpur, Jharkhand</p><a href="mailto:support@nisecomport.com">support@nisecomport.com <ArrowUpRight size={14}/></a></div></div><div className="container footer-bottom"><span>© {new Date().getFullYear()} NISE COMPORT. All rights reserved.</span><span>Independent service provider · Final approvals rest with the relevant authority.</span><div><Link href="/privacy">Privacy</Link><Link href="/terms">Terms</Link></div></div></footer>
    <div className="mobile-dock"><Link href="/services"><Landmark size={18}/><span>Services</span></Link><Link href="/print"><Printer size={18}/><span>Print</span></Link><Link href="/profile"><FileText size={18}/><span>Track</span></Link><Link href="/login"><span className="dock-login">↗</span><span>Account</span></Link></div>
  </>;
}
