"use client";

import SiteHeader from "@/components/site-header";
import { useState } from "react";
import Link from "next/link";
import { ArrowRight, Check, Clock3, FileText, Gift, History, MapPin, Printer, ShieldCheck, UserRound, WalletCards } from "lucide-react";

type DemoSection = "overview" | "requests" | "history" | "prints" | "wallet" | "vouchers" | "profile" | "security";
const sections: { id: DemoSection; title: string; icon: typeof UserRound }[] = [
  { id: "overview", title: "Overview", icon: UserRound },
  { id: "requests", title: "My requests", icon: FileText },
  { id: "history", title: "Request history", icon: History },
  { id: "prints", title: "Print orders", icon: Printer },
  { id: "wallet", title: "Wallet", icon: WalletCards },
  { id: "vouchers", title: "Vouchers & offers", icon: Gift },
  { id: "profile", title: "Profile details", icon: UserRound },
  { id: "security", title: "Sign-in & privacy", icon: ShieldCheck },
];

export default function DemoProfile() {
  const [section, setSection] = useState<DemoSection>("overview");
  const [sampleCredit, setSampleCredit] = useState(0);
  const balance = 250 + sampleCredit;
  const content = (() => {
    switch (section) {
      case "overview": return <>
        <section className="profile-welcome-card"><div><span className="eyebrow">LOCAL PREVIEW ACCOUNT</span><h2>Good to see you,<br/><em>Shubham.</em></h2><p>Explore how requests, history, wallet entries and profile details will appear for a signed-in customer.</p><Link href="/services" className="button button-cream">Browse services <ArrowRight size={15}/></Link></div><div className="profile-welcome-art"><UserRound size={44}/><i/><i/><i/></div></section>
        <section className="profile-metric-grid"><DemoMetric icon={<FileText size={18}/>} value="1" label="Open request"/><DemoMetric icon={<Printer size={18}/>} value="0" label="Print orders"/><DemoMetric icon={<WalletCards size={18}/>} value={`₹${balance.toFixed(2)}`} label="Sample wallet"/></section>
        <div className="profile-panel profile-overview-panel"><div className="profile-panel-heading"><span className="eyebrow eyebrow-muted">LATEST ACTIVITY</span><h2>Request in review</h2><p>This example shows the reference and status attached to a customer request.</p></div><DemoRequest/><button className="profile-text-button" type="button" onClick={() => setSection("requests")}>Open request details <ArrowRight size={14}/></button></div>
      </>;
      case "requests": return <div className="profile-panel"><DemoHeading eyebrow="IN PROGRESS" title="My service requests" text="Follow the request reference, submitted note and current review state."/><DemoRequest full/><p className="demo-disclaimer">Sample only: this preview request is not stored in PostgreSQL and is not sent to the service team.</p><Link href="/services/pan-card-jamshedpur" className="profile-text-button">Read the PAN service guide <ArrowRight size={14}/></Link></div>;
      case "history": return <div className="profile-panel"><DemoHeading eyebrow="RECENT ACTIVITY" title="Request history" text="A customer can review earlier outcomes and ongoing requests here."/><div className="demo-history-list"><article><span className="history-dot history-done"><Check size={13}/></span><div><b>Document scan request</b><small>NC-DEMO-000 · Completed · 12 Sep 2026</small><p>Scanned copies prepared for pickup at the service desk.</p></div><span className="history-status">Completed</span></article><article><span className="history-dot"><Clock3 size={13}/></span><div><b>PAN application assistance</b><small>NC-DEMO-001 · In review · 27 Sep 2026</small><p>The team is checking the request details before confirming next steps.</p></div><span className="history-status">In review</span></article></div></div>;
      case "prints": return <div className="profile-panel"><DemoHeading eyebrow="DOCUMENT SERVICES" title="Print orders" text="Print requests will show uploaded file, options, estimate and pickup or delivery status."/><div className="profile-empty-state"><span><Printer size={20}/></span><h3>No sample print orders</h3><p>Use the print page to inspect the estimate request flow. Submitting from this demo account does not create a real job.</p><Link href="/print" className="button button-green">Open print request <ArrowRight size={15}/></Link></div></div>;
      case "wallet": return <div className="profile-panel"><DemoHeading eyebrow="CUSTOMER REWARDS" title="Wallet & credits" text="This clearly labelled sample shows how staff-recorded wallet changes will appear."/><div className="demo-wallet-card"><div className="demo-wallet-balance"><span><WalletCards size={18}/> DEMO WALLET BALANCE</span><strong>₹{balance.toFixed(2)}</strong><small>Sample funds only · no real payment is involved</small></div><div className="demo-wallet-ledger"><h3>Recent wallet activity</h3><div><span><b>Welcome preview credit</b><small>Sample demo entry</small></span><strong className="credit-value">+₹250.00</strong></div>{sampleCredit > 0 && <div><span><b>Test credit added</b><small>Temporary preview only</small></span><strong className="credit-value">+₹{sampleCredit.toFixed(2)}</strong></div>}<button className="button button-green" type="button" onClick={() => setSampleCredit((value) => value + 100)}>Add ₹100 sample credit</button><small>This button changes only this preview and does not create a database transaction.</small></div></div></div>;
      case "vouchers": return <div className="profile-panel"><DemoHeading eyebrow="SAVINGS & PROMOTIONS" title="Vouchers & offers" text="Personal voucher details will show here when the account has an assigned offer."/><div className="profile-voucher-panel"><Gift size={22}/><div><b>No live voucher is configured for this preview.</b><p>Public offers and their terms are shown on the offers page. A real voucher will display its code, value and expiry here.</p><Link href="/offers">View offers <ArrowRight size={14}/></Link></div></div></div>;
      case "profile": return <div className="profile-panel"><DemoHeading eyebrow="PERSONAL INFORMATION" title="Profile details" text="A real customer can update contact and location details here. This local preview does not save changes."/><div className="profile-security-list"><article><UserRound size={19}/><div><b>Full name</b><p>Shubham Raj · sample preview</p></div></article><article><ShieldCheck size={19}/><div><b>Verified email</b><p>demo@nisecomport.test · local demo login</p></div></article><article><MapPin size={19}/><div><b>City and contact details</b><p>Entered by the customer and saved to the PostgreSQL profile in a real account.</p></div></article></div><p className="demo-disclaimer">The demo has no real person’s email, phone, address, or account data.</p></div>;
      case "security": return <div className="profile-panel"><DemoHeading eyebrow="ACCOUNT ACCESS" title="Sign-in & privacy" text="Review which sign-in method is active and how personal data is handled."/><div className="profile-security-list"><article><ShieldCheck size={19}/><div><b>Local demo session</b><p>This session uses a development-only preview cookie. It is not a real customer account.</p></div><span>Preview</span></article><article><UserRound size={19}/><div><b>Real customer sign-in</b><p>Email address and password or a one-time code sent through the configured SMTP mailbox.</p></div><span>Available</span></article><article><MapPin size={19}/><div><b>Google sign-in</b><p>Not connected in this version. Contact details such as a mobile number are entered by the user.</p></div><span>Not connected</span></article></div><p className="profile-security-tip"><b>Never share:</b> email OTPs, passwords, Aadhaar OTPs or banking PINs.</p></div>;
    }
  })();
  return <main className="profile-page"><SiteHeader/><div className="container profile-container"><div className="demo-mode-banner"><ShieldCheck size={18}/><span><b>Local preview account</b><small>All requests, wallet activity and profile examples are sample data and are not saved.</small></span></div>
    <div className="profile-workspace"><aside className="profile-sidebar"><div className="profile-identity"><div className="profile-avatar"><UserRound size={24}/></div><div><b>Shubham Raj</b><small>demo@nisecomport.test</small></div></div><span className="verified-badge"><ShieldCheck size={13}/> Demo account</span><div className="sidebar-divider"/><nav className="profile-section-nav" aria-label="Profile sections">{sections.map(({ id, title, icon: Icon }) => <button type="button" key={id} className={section === id ? "active" : ""} onClick={() => setSection(id)}><Icon size={16}/><span>{title}</span></button>)}</nav><Link className="demo-signup-link" href="/signup">Create a real account <ArrowRight size={14}/></Link></aside>
      <section className="profile-main-panel" aria-live="polite"><div className="profile-mobile-section-select"><label htmlFor="demo-profile-section">Profile section</label><select id="demo-profile-section" value={section} onChange={(event) => setSection(event.target.value as DemoSection)}>{sections.map((item) => <option key={item.id} value={item.id}>{item.title}</option>)}</select></div>{content}</section>
    </div><p className="profile-footnote"><Check size={14}/> Demo content helps you inspect the flow. Real requests and profiles require your configured PostgreSQL database and SMTP email.</p>
  </div></main>;
}

function DemoHeading({ eyebrow, title, text }: { eyebrow: string; title: string; text: string }) { return <div className="profile-panel-heading"><span className="eyebrow eyebrow-muted">{eyebrow}</span><h2>{title}</h2><p>{text}</p></div>; }
function DemoMetric({ icon, value, label }: { icon: React.ReactNode; value: string; label: string }) { return <article className="profile-metric"><span>{icon}</span><div><b>{value}</b><small>{label}</small></div></article>; }
function DemoRequest({ full = false }: { full?: boolean }) { return <article className="profile-record"><span className="request-icon"><Clock3 size={18}/></span><div className="profile-record-copy"><b>PAN application assistance</b><small>NC-DEMO-001 · 27 Sep 2026</small><p>Sample request: the team is checking details before confirming the next steps.</p>{full && <p>In a real account, this page includes the details and supporting documents you submitted, the status timeline, service checklist and staff follow-up.</p>}</div><span className="request-status status-reviewing"><i/>In review</span></article>; }
