"use client";
import SiteHeader from "@/components/site-header";
import { useState } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import BrandWordmark from "@/components/brand-wordmark";
import { ArrowRight, Check, Clock3, Gift, History, LogOut, ShieldCheck, WalletCards } from "lucide-react";

export default function DemoProfile() {
  const router = useRouter();
  const [busy, setBusy] = useState(false);
  const [sampleCredit, setSampleCredit] = useState(0);
  async function signOut() { setBusy(true); await fetch("/api/auth/session", { method: "DELETE" }); router.replace("/"); router.refresh(); }
  const balance = 250 + sampleCredit;
  return <main className="profile-page"><SiteHeader/><div className="container profile-container"><header className="demo-profile-header"><Link className="brand" href="/"><BrandWordmark/></Link><button className="profile-logout" onClick={signOut} disabled={busy}><LogOut size={15}/>{busy ? "Signing out…" : "Sign out"}</button></header>
    <div className="demo-mode-banner"><ShieldCheck size={18}/><span><b>Local preview account</b><small>This is sample data for checking the customer flow. Demo activity is not stored in PostgreSQL.</small></span></div>
    <div className="profile-greeting"><div><span className="eyebrow eyebrow-muted">CUSTOMER ACCOUNT · DEMO</span><h1>Good to see you, <em>Shubham.</em></h1><p>This is your profile home. Use the sections below to inspect sample requests, history and wallet.</p></div></div>
    <nav className="demo-profile-nav" aria-label="Profile sections"><a href="#requests"><Clock3 size={16}/> Requests</a><a href="#history"><History size={16}/> History</a><a href="#wallet"><WalletCards size={16}/> Wallet</a><a href="#rewards"><Gift size={16}/> Vouchers</a></nav>
    <section className="demo-profile-section" id="requests"><div className="demo-section-heading"><div><span className="eyebrow eyebrow-muted">IN PROGRESS</span><h2>Your service requests</h2><p>Open a request to see what it means and which service page explains the steps.</p></div><span className="demo-count">1 request</span></div>
      <article className="demo-request-card"><div className="request-icon"><Clock3 size={18}/></div><div className="demo-request-body"><span className="eyebrow eyebrow-muted">SAMPLE · NC-DEMO-001</span><h3>PAN application assistance</h3><p>Submitted 27 Sep 2026 · Status: in review</p><details className="demo-request-details"><summary>What is this request?</summary><p>This sample represents a customer asking NISE COMPORT for help preparing a PAN application or correction. In a real account, the request description, attached documents, reference number and staff status updates are shown here. NISE COMPORT assists with the application; the authorised PAN provider and tax authority process and issue the PAN.</p><Link href="/services/pan-card-application-jamshedpur">Read PAN service details <ArrowRight size={14}/></Link></details></div><span className="request-status status-reviewing"><i/>In review</span></article>
      <div className="demo-profile-actions"><Link className="button button-green" href="/services">Start a service request <ArrowRight size={15}/></Link><Link className="button button-dark" href="/print">Request a print estimate <ArrowRight size={15}/></Link></div>
    </section>
    <section className="demo-profile-section" id="history"><div className="demo-section-heading"><div><span className="eyebrow eyebrow-muted">RECENT ACTIVITY</span><h2>Request history</h2><p>Sample history shows how completed and pending work will appear.</p></div></div><div className="demo-history-list"><article><span className="history-dot history-done"><Check size={13}/></span><div><b>Document scan request</b><small>NC-DEMO-000 · Completed · 12 Sep 2026</small><p>Scanned copies prepared for pickup at the service desk.</p></div><span className="history-status">Completed</span></article><article><span className="history-dot"><Clock3 size={13}/></span><div><b>PAN application assistance</b><small>NC-DEMO-001 · In review · 27 Sep 2026</small><p>Team is checking the request details before confirming next steps.</p></div><span className="history-status">In review</span></article></div></section>
    <section className="demo-profile-section" id="wallet"><div className="demo-section-heading"><div><span className="eyebrow eyebrow-muted">CUSTOMER REWARDS</span><h2>Wallet &amp; credits</h2><p>Demo balance and ledger. Live balances need recorded credits from the service team.</p></div></div><div className="demo-wallet-card"><div className="demo-wallet-balance"><span><WalletCards size={18}/> DEMO WALLET BALANCE</span><strong>₹{balance.toFixed(2)}</strong><small>Sample funds only · no real money or payment is involved</small></div><div className="demo-wallet-ledger"><h3>Recent wallet activity</h3><div><span><b>Welcome preview credit</b><small>Sample demo entry</small></span><strong className="credit-value">+₹250.00</strong></div>{sampleCredit>0&&<div><span><b>Test credit added</b><small>Temporary browser preview only</small></span><strong className="credit-value">+₹{sampleCredit.toFixed(2)}</strong></div>}<button className="button button-green" type="button" onClick={()=>setSampleCredit(value=>value+100)}>Add ₹100 sample credit</button><small>For real customer accounts, approved credits are posted by staff. This demo button does not create a database transaction.</small></div></div></section>
    <section className="demo-profile-section" id="rewards"><div className="demo-section-heading"><div><span className="eyebrow eyebrow-muted">VOUCHERS &amp; OFFERS</span><h2>Customer offers</h2><p>Active promotion terms are shown before a customer uses a voucher.</p></div></div><div className="demo-voucher-card"><Gift size={20}/><div><b>No live offer configured in this preview</b><p>Visit Offers &amp; vouchers to ask about current promotions. A real voucher is validated when entered in a supported request flow.</p></div><Link className="arrow-link" href="/offers">View offers <ArrowRight size={14}/></Link></div></section>
    <p className="profile-footnote"><Check size={14}/> Demo content lets you inspect the interface. PostgreSQL, SMTP and private storage are needed for persistent customer accounts and uploads.</p>
  </div></main>;
}
