"use client";
import { useState } from "react";
import { panIssues, panSources } from "@/lib/pan-content";
import { validateTracking } from "@/lib/pan-validation";
export function PanStatusTool() {
 const [provider,setProvider]=useState("protean"),[reference,setReference]=useState(""),[error,setError]=useState(""),[ready,setReady]=useState(false);
 return <section className="pan-card"><h2>Check your tracking reference</h2><p>This checks formatting only. Live status and CAPTCHA verification take place on the official provider website.</p><form onSubmit={e=>{e.preventDefault();const message=validateTracking(provider,reference);setError(message);setReady(!message);}}><label>Provider<select value={provider} onChange={e=>{setProvider(e.target.value);setReady(false);}}><option value="protean">Protean (formerly NSDL)</option><option value="uti">UTIITSL</option></select></label><label>{provider==="protean"?"15-digit acknowledgement":"Application coupon reference"}<input required value={reference} maxLength={30} onChange={e=>{setReference(e.target.value);setReady(false);}} autoComplete="off"/></label><button className="button button-green">Check format</button>{error&&<p role="alert">{error}</p>}{ready&&<div role="status"><p>Basic format checked. Keep your receipt ready; this does not verify that the application exists. Enter the reference and any other requested details on the official page.</p><a className="button button-outline" target="_blank" rel="noreferrer" href={provider==="protean"?panSources.proteanTrack:panSources.utiTrack}>Open official {provider==="protean"?"Protean":"UTIITSL"} tracker ↗</a></div>}</form></section>;
}
export function PanIssueSearch(){const [query,setQuery]=useState("");const items=panIssues.filter(([title,body])=>(title+body).toLowerCase().includes(query.toLowerCase()));return <section><label>Find help with a PAN issue<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Try rejected, name, OTP or delivery"/></label><p>{items.length} guides</p><div className="pan-grid">{items.map(([title,body])=><article className="pan-card" key={title}><h3>{title}</h3><p>{body}</p></article>)}</div>{!items.length&&<p>No matching issue. Try another term or contact the service team.</p>}</section>;}
